### DISCUSSION TITLE
dubbo 2.7.18  使用 nacos 作为配置中心，dubbo-admin下发动态配置（应用级负载均衡策略），负载均衡不生效。

### DISCUSSION THREAD

**Discussion by burger-cyx** [apache/dubbo#13892] [Question]
dubbo 2.7.18
nacos 2.0.3
dubbo-admin 0.3.0

nacos配置如下
 
```
configVersion: v2.7
configs:
- enabled: true
  parameters:
    loadbalance: leastactive
  side: consumer
  type: balancing
enabled: true
key: dubbo-provider
scope: application
```

nacos下发动态配置（应用级负载均衡策略），负载均衡不生效
应用级服务权重，应用级服务禁用都生效
