### DISCUSSION TITLE
When dubbo is connected to the xds protocol, how does the name of the dubbo application correspond to the service name obtained by istio?

### DISCUSSION THREAD

**Discussion by daizhenyu** [apache/dubbo#14103] [Question]
### Pre-check

- [X] I am sure that all the content I provide is in English.

### Apache Dubbo Component

Java SDK (apache/dubbo)

### Details

When dubbo is connected to the xds protocol, how does the name of the dubbo application correspond to the service name obtained by istio? In addition to that, which module is the xds code in at the moment?

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by AlbumenJ** [comment]
@Tomoko-hjf PTAL

**Comment by Fancy-hjyp** [comment]
@daizhenyu  In the istio system, the `Application` concept of Dubbo is equivalent to the `Service` of istio, and there is a one-to-one correspondence between them. 

Suppose have a service named `dubco-demo-xds-provider` now，after user sets the service route through the `hosts` field of the `VirtualService` resource in istio, the Consumer side needs to use `@DubboReference(providedBy = "dubco-demo-xds-provider ")` annotation to specify the service name to access.

Further, mapping relationships between `Application` of Dubbo and `Service` of istio are implemented by parsing RDS resources.

```yml
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: dubbo-demo-xds-provider
spec:
  hosts:
    # specify service name of istio
    - dubbo-demo-xds-provider
  http:
  - match:
    - uri:
        prefix: /reviews
    route:
    - destination:
        host: reviews
```
```java
@SpringBootApplication
@Service
@EnableDubbo
public class XdsConsumerApplication {

    @DubboReference(providedBy = "dubbo-demo-xds-provider")
    private DemoService demoService;

    public static void main(String[] args)  {
    
    }
}
```

The implementation of the old version is in `dubbo-xds` module of `https://github.com/apache/dubbo-spi-extensions`, and the new beta version is in `dubbo-xds` module of `https://github.com/apache/dubbo/tree/3.3-dev-xds` ~
