### DISCUSSION TITLE
[Q/A][Java SDK (Component)] How to disable Metric in dubbo 3.2.x

### DISCUSSION THREAD

**Discussion by lossend** [apache/dubbo#14309] [Question]
### Pre-check

- [X] I am sure that all the content I provide is in English.

### Apache Dubbo Component

Java SDK (apache/dubbo)

### Details

the property"dubbo.metrics.enabled=false", is not working

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by aofall** [comment]
You can refer to the [official documentation](https://cn.dubbo.apache.org/zh-cn/overview/mannual/java-sdk/reference-manual/config/properties/#metrics) for configuration，Just keep the config under `dubbo.metrics` empty. Or try this config.

```
dubbo:
  metrics:
    prometheus:
      exporter:
        enabled: false
      pushgateway:
        enabled: false
    aggregation: 
      enabled: false
```
