### DISCUSSION TITLE
[Q/A][Java SDK (Component)] Nacos2.4.1 opening authentication and  Dubbo registered 403

### DISCUSSION THREAD

**Discussion by 48038411** [apache/dubbo#14496] [Question]
### Pre-check

- [X] I am sure that all the content I provide is in English.

### Apache Dubbo Component

Java SDK (apache/dubbo)

### Details

My nacos version is 2.4.1, dubbo version is 3.2.14, and spring boot version is 3.3.1. When I open the nacos server authentication, "Failed to create nacos config service client. Reason: server status check failed". When I debug locally, I found that when Dubbo obtained the dubbo-nacos-test configuration, the error 403 was not authorized
My configuration is as follows
```
dubbo:
  application:
    name: travel
    logger: slf4j
  registry:
    address: nacos://@nacos.server-addr@
    check: false
    username: @nacos.username@
    password: @nacos.password@
    group: travel
  protocol:
    name: dubbo
    port: -1
  metrics:
    enable-metrics-init: false
  consumer:
    check: false
    filter: consumerFilter
    provider-namespace: @nacos.namespace@
  provider:
    filter: providerFilter
  config-center:
    namespace: @nacos.namespace@
    username: @nacos.username@
    password: @nacos.password@
```
I am sure that the username and password read from the environment variable are correct. I do not know if I have missed any configuration. Please let me know

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)
