### DISCUSSION TITLE
DUBBO 3.1.4 Unable to register under two different namespaces in one nacos;DUBBO 3.1.4 无法注册到一个nacos中两个不同的namespace下

### DISCUSSION THREAD

**Discussion by TOP-LH** [apache/dubbo#14961] [Question] [answered]
### Pre-check

- [X] I am sure that all the content I provide is in English.

### Apache Dubbo Component

Java SDK (apache/dubbo)

### Details

DUBBO VERSION: 3.1.4
DUBBO SPRINGBOOT VERSION: 3.1.4
SPRINGBOOT VERSION: 2.3.12.RELEASE
JDK VERSION: 8
bootstrap.yml
```yml

spring:
  cloud:
    nacos:
      discovery:
        # 注册中心地址
        server-addr: 10.XX.10.XX:8848
        # 命名空间
        namespace: 79883141-087a-4f4f-9a13-f2c42bb73e14
        namespace2: b84945ff-30e0-4cf1-9e20-f73619b3d3f2
      config:
        # 注册中心地址
        server-addr: ${spring.cloud.nacos.discovery.server-addr}
        # 命名空间
        namespace: ${spring.cloud.nacos.discovery.namespace}
        # 配置格式
        file-extension: yaml

dubbo:
  application:
    logger: slf4j
    qos-enable: false
    id: ${spring.application.name}
    name: ${spring.application.name}
    register-mode: instance
    service-discovery:
      migration: FORCE_APPLICATION
  registry:
    - address: nacos://${spring.cloud.nacos.discovery.server-addr}
      group: DUBBO_GROUP
      parameters:
        namespace: ${spring.cloud.nacos.discovery.namespace}
    - address: nacos://${spring.cloud.nacos.discovery.server-addr}
      group: DUBBO_GROUP
      parameters:
        namespace: ${spring.cloud.nacos.discovery.namespace2}
  protocol:
    name: dubbo
    port: -1
    threadpool: cached
    dispatcher: message
    serialization: hessian2
  provider:
    timeout: 30000
    retries: 0
    group: DUBBO_GROUP
  consumer:
    check: false
    group: DUBBO_GROUP

```

请问如何可以同时注册到一个nacos下两个不同的namespace下? 我的配置文件是否有问题? 我启动后无法注册到两个namespace下, 请求帮助, 谢谢
How can I register to two different namespaces under one nacos at the same time? Is there something wrong with my configuration file? I can't register under both namespaces after startup, please help, thank you!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)
