### DISCUSSION TITLE
[Q/A][Java SDK (Component)] Serializaion the client used

### DISCUSSION THREAD

**Discussion by freedom0123** [apache/dubbo#15007] [Question]
### Pre-check

- [X] I am sure that all the content I provide is in English.

### Apache Dubbo Component

Java SDK (apache/dubbo)

### Details

Environment: JDK 1.8 、SpringBoot 2.7.18 ，Dubbo 3.2.0

I want to use the serialization  of the kryo. The server privider config is as follows:
```yaml
dubbo:
  application:
    name: ${spring.application.name}
  protocol:
    name: dubbo
    serialization: kryo
```
Then， The Consumer the code is as follows:
```java
    @DubboReference(url = "dubbo://192.168.1.9:20880/com.coding.api.UserService")
    private UserService userService;
```
 In consumer, I don't use the dependency of the kryo， But  The server and the client can interact normally.

So I want to know the serializaion the client used;

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)
