### ISSUE TITLE
Provider服务已成功注册，Consumer启动报没有可用Provider 

### ISSUE THREAD

**Issue by pengsuwei** [apache/dubbo#10169]
Provider注册：
![image](https://user-images.githubusercontent.com/81412734/174021718-e42b2b85-bb41-4c9c-a1dd-51064816a0e2.png)

Consumer报错信息：
2022-06-16 15:51:58:259|DESKTOP-5V7AMPK|/|main|ERROR|o.s.b.SpringApplication:830|Application run failed java.lang.IllegalStateException: Failed to check the status of the service com.ad.platform.common.dubbo.api.ad.exchange.BiddingAdsService. No provider available for the service ad-platform/com.ad.platform.common.dubbo.api.ad.exchange.BiddingAdsService from the url consumer://2.0.1.87/com.ad.platform.common.dubbo.api.ad.exchange.BiddingAdsService?application=ad-platform-engine&background=false&dubbo=2.0.2&group=ad-platform&interface=com.ad.platform.common.dubbo.api.ad.exchange.BiddingAdsService&metadata-type=remote&methods=biddingAdsAsync,biddingAds&pid=7656&qos.enable=false&register.ip=2.0.1.87&release=3.0.6&side=consumer&sticky=false&timestamp=1655365904207 to the consumer 2.0.1.87 use dubbo version 3.0.6
	at org.apache.dubbo.config.ReferenceConfig.checkInvokerAvailable(ReferenceConfig.java:544)
	at org.apache.dubbo.config.ReferenceConfig.init(ReferenceConfig.java:287)
	at org.apache.dubbo.config.ReferenceConfig.get(ReferenceConfig.java:219)
	at org.apache.dubbo.config.utils.SimpleReferenceCache.get(SimpleReferenceCache.java:110)
	at org.apache.dubbo.config.deploy.DefaultModuleDeployer.lambda$referServices$6(DefaultModuleDeployer.java:384)
	at java.base/java.util.concurrent.ConcurrentHashMap$ValuesView.forEach(ConcurrentHashMap.java:4772)
	at org.apache.dubbo.config.deploy.DefaultModuleDeployer.referServices(DefaultModuleDeployer.java:364)
	at org.apache.dubbo.config.deploy.DefaultModuleDeployer.start(DefaultModuleDeployer.java:151)
	at org.apache.dubbo.config.spring.context.DubboDeployApplicationListener.onContextRefreshedEvent(DubboDeployApplicationListener.java:111)
	at org.apache.dubbo.config.spring.context.DubboDeployApplicationListener.onApplicationEvent(DubboDeployApplicationListener.java:100)
	at org.apache.dubbo.config.spring.context.DubboDeployApplicationListener.onApplicationEvent(DubboDeployApplicationListener.java:45)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.doInvokeListener(SimpleApplicationEventMulticaster.java:176)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:169)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:143)
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:421)
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:378)
	at org.springframework.context.support.AbstractApplicationContext.finishRefresh(AbstractApplicationContext.java:938)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:586)
	at org.springframework.boot.web.reactive.context.ReactiveWebServerApplicationContext.refresh(ReactiveWebServerApplicationContext.java:64)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:740)
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:415)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:303)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1312)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1301)
	at com.ad.platform.engine.Application.main(Application.java:28)

Provider Config：
```
dubbo:
  application:
    name: ad-platform-exchange
  registry:
    address: nacos://servicecenter-dev-drcn.inner.platform.com:8848?username=xxx&password=xxx
    parameters:
      namespace: 1e22e212-6859-42c6-b89d-d33fdcef939c
    group: ad-platform
  protocol:
    name: tri
    port: -1
```

Consumer Config：
```
dubbo:
  application:
    name: ad-platform-engine
  registry:
    address: nacos://servicecenter-dev-drcn.inner.platform.com:8848?username=xxx&password=xxx
    parameters:
      namespace: 1e22e212-6859-42c6-b89d-d33fdcef939c
    group: ad-platform
  protocol:
    name: tri
    port: -1
```
