### ISSUE TITLE
配置规则中mock参数不生效

### ISSUE THREAD

**Issue by Trydamere** [apache/dubbo#10246]
- [ ] I have searched the [issues](https://github.com/apache/dubbo/issues) of this repository and believe that this is not a duplicate.

### Environment

* Dubbo version: 3.0
* Operating System version: win10
* Java version: 1.8

### Steps to reproduce this issue

1. run `BasicProvider` on dubbo-samples-servicelevel-override
2. config rule on dubbo-admin
```
configVersion: v2.7
scope: service
key: org.apache.dubbo.samples.governance.api.DemoService
enabled: true
configs:
- addresses: [0.0.0.0]
  side: consumer
  parameters:
    force: return null
```
4. run `BasicConsumer`, config rule did not work

在动态配置中配置mock参数，mock参数没有生效，原因在于DynamicDirectory的ConsumerUrl方法得到的是没有override的url，需要修改getConsumerUrl方法。

### Expected Behavior

The `sayHello` returned null.

### Actual Behavior

The `sayHello` called the provider.
