### ISSUE TITLE
Combined with Spring boot, file configuration, multi-service interface configuration only takes effect for one service(Springboot文件形式配置, 多服务接口配置仅一个服务生效)

### ISSUE THREAD

**Issue by wlf950328** [apache/dubbo#10475]
- [√] I have searched the [issues](https://github.com/apache/dubbo/issues) of this repository and believe that this is not a duplicate.

### Environment

* Dubbo version: 2.7.8 & 3.0.11
* Operating System version: Win10
* Java version: JDK 1.8

### Steps to reproduce this issue

1. Create multiple providers(创建多个服务生产者)
2. Multi-service interface configuration in consumer configuration file(在消费者服务配置文件中配置多服务接口信息)
3. Run and Test (运行并调用测试)

Pls. provide [GitHub address] to reproduce this issue.

Below is the code sample for both versions. (Only the version is different)
以下是两个版本的代码示例(仅版本不同)
https://github.com/wlf950328/dubbo-demo-2.7.8 (dubbo-2.7.8)
https://github.com/wlf950328/dubbo-demo-3.0.11 (dubbo-3.0.11)

### Expected Behavior

I hope the configured multiple services can take effect. 
我希望消费者配置的多服务都能正确生效

### Actual Behavior

In fact, although there is no abnormality, only one multi-service configured by the consumer takes effect, and the rest of the service configurations will have the following behaviors:
· If the method name is the same as the effective service method name, use the configuration of the effective interface
· Otherwise, use the default configuration (for example, the interface timeout is the default 1s)

实际虽然没有任何异常, 但是消费者配置的多服务仅生效了一个, 而其余的服务配置会有如下行为:
· 如果方法名与生效的服务方法名相同, 那么使用生效的配置
· 否则使用默认配置(比如接口超时时间为默认的1s)

### Something Else
In the demo, the configuration file uses the yaml format. I also use the properties format configuration, the problem also exists.
在示例中, 配置文件是yaml格式的.  我另外还使用了 properties 格式的配置, 问题同样存在

Paste the configuration of the consumer service below.
下面贴上消费者服务的配置

yaml:
```
dubbo:
  application:
    name: dubbo-demo-consumer
  registry:
    address: zookeeper://127.0.0.1:2181
  consumers:
    userInfoService1: # 有效 efficient
      parameters:
        getUserInfoById:
          timeout: 4000
          async: false
          sent: false
          retries: 1
    userInfoService2: # 无效 invalid
      parameters:
        getUserInfo:
          timeout: 1200
          async: false
          sent: false
          retries: 1
        getUserInfoById:
          timeout: 2000
          async: false
          sent: false
          retries: 3
```

properties:
```
dubbo.application.name=dubbo-demo-consumer
dubbo.registry.address=zookeeper://127.0.0.1:2181
dubbo.consumers.userInfoService1.parameters[getUserInfoById.timeout]=4000
dubbo.consumers.userInfoService2.parameters[getUserInfoById.retries]=1
dubbo.consumers.userInfoService2.parameters[getUserInfoById.timeout]=2000
dubbo.consumers.userInfoService2.parameters[getUserInfo.retries]=3
dubbo.consumers.userInfoService2.parameters[getUserInfo.timeout]=1200
dubbo.consumers.userInfoService2.parameters[getUserInfo.retries]=1
```
