### ISSUE TITLE
dubbo Proxyless 模式与istio交互问题

### ISSUE THREAD

**Issue by wucheng1997** [apache/dubbo#10524]
- [ ] I have searched the [issues](https://github.com/apache/dubbo/issues) of this repository and believe that this is not a duplicate.

## Ask your question here

版本dubbo-3.1.0 Proxyless 模式
使用的时候发现dubbo并不支持istio与envoy之间的一些流量治理规则，类似于超时重试，负载均衡等

```
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: vs-dubbo-samples-xds-provider
  namespace: dubbo-proxyless
spec:
  http:
  - route:
    - destination:
        host: dubbo-samples-xds-provider.dubbo-proxyless.svc.cluster.local
        port:
          number: 80
    timeout: 9s
    retries:
      attempts: 3
      perTryTimeout: 3s
```

参考配置如上，请教一下，是目前dubbo不支持相应的功能，还是使用方式和传统的istio Sidecar，目前没有看到相关文档
