### ISSUE TITLE
3.1.1 使用应用级服务发现一直提示找不到消费者

### ISSUE THREAD

**Issue by luger1990** [apache/dubbo#10747]
生产者配置:
```
server:
  port: @server.port@
  tomcat:
    uri-encoding: UTF-8
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
spring:
  application:
    name: provider-service
  profiles:
    active: @profiles.active@
  main:
    allow-bean-definition-overriding: true
    allow-circular-references: true
  mvc:
    hiddenmethod:
      filter:
        enabled: true
#  cloud:
#    nacos:
#      discovery:
#        server-addr: 192.168.100.121:8848

management:
  endpoints:
    web:
      exposure:
        include: "*"



dubbo:
  application:
    name: ${spring.application.name}
    id: ${spring.application.name}
    register-mode: instance
  protocol:
    id: dubbo
    name: dubbo
    port: -1
  registry:
    address: nacos://192.168.100.121:8848 #?registry-type=service
  config-center:
    address: nacos://192.168.100.121:8848
  metadata-report:
    address: nacos://192.168.100.121:8848
  scan:
    base-packages: me.luger
```

消费者配置:
```
server:
  port: 8886
  tomcat:
    uri-encoding: UTF-8
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
spring:
  application:
    name: consumer-service
  profiles:
    active: test
  main:
    allow-bean-definition-overriding: true
    allow-circular-references: true
  mvc:
    hiddenmethod:
      filter:
        enabled: true
#  cloud:
#    nacos:
#      discovery:
#        server-addr: 192.168.100.121:8848

management:
  endpoints:
    web:
      exposure:
        include: "*"

dubbo:
  application:
    name: ${spring.application.name}
    id: ${spring.application.name}
    register-mode: instance
    service-discovery:
      migration: FORCE_APPLICATION
  protocol:
    id: dubbo
    name: dubbo
    port: -1
  registry:
    address: nacos://192.168.100.121:8848 #?registry-type=service
    cloud:
      subscribed-services: provider-service
    config-center:
      address: nacos://192.168.100.121:8848
    metadata-report:
      address: nacos://192.168.100.121:8848
  scan:
    base-packages: me.luger
  consumer:
    protocol: dubbo
```

去掉应用级服务发现`register-mode: instance`就是可以的. 很奇怪。 是配置哪里不对吗
