### ISSUE TITLE
dubbo.consumer.tag not work on 3.x

### ISSUE THREAD

**Issue by AlbumenJ** [apache/dubbo#10765]
- [ ] I have searched the [issues](https://github.com/apache/dubbo/issues) of this repository and believe that this is not a duplicate.

### Environment

* Dubbo version: xxx
* Operating System version: xxx
* Java version: xxx

### Steps to reproduce this issue

1. xxx
2. xxx
3. xxx

```properties
dubbo.provider.tag=dev
dubbo.consumer.tag=dev
```

Pls. provide [GitHub address] to reproduce this issue.

### Actual Behavior

If there is an exception, please attach the exception trace:

```
Just put your stack trace here!
```

**Comment by pandaapo** [comment]
I used `dubbo-demo-spring-boot` to try to reproduce this bug, but it seems to work well.

I modified the provider `application.yml`:
```
dubbo:
  application:
    name: dubbo-springboot-demo-provider
  protocol:
    name: dubbo
    port: -1
  provider:
    tag: tagA # another instance is configured as tagB
  registry:
    id: zk-registry
    address: zookeeper://127.0.0.1:2181
#  config-center:
#    address: zookeeper://127.0.0.1:2181
#  metadata-report:
#    address: zookeeper://127.0.0.1:2181
```
I modified the consumer `application.yml`:
```
dubbo:
  application:
    name: dubbo-springboot-demo-consumer
#  protocol:
#    name: dubbo
#    port: -1
  consumer:
    tag: tagB
  registry:
    id: zk-registry
    address: zookeeper://127.0.0.1:2181
#  config-center:
#    address: zookeeper://127.0.0.1:2181
#  metadata-report:
#    address: zookeeper://127.0.0.1:2181
```

This is the result of running consumer:
```
result: I am tag B, Hello world
result: I am tag B, Hello world
result: I am tag B, Hello world
result: I am tag B, Hello world
result: I am tag B, Hello world
result: I am tag B, Hello world
result: I am tag B, Hello world
result: I am tag B, Hello world
result: I am tag B, Hello world
result: I am tag B, Hello world
``` 

Does this bug only occur in some specified situation?
