### ISSUE TITLE
How to set map values to parameters of ApplicationConfig by spring boot yaml 

### ISSUE THREAD

**Issue by yuanxuzhang** [apache/dubbo#10969]
How to set map values to parameters of ApplicationConfig by spring boot yaml ？
It seems only support primitive value converted by ClassUtils.convertPrimitive。is there anyway can resolve this？

**Comment by AlbumenJ** [comment]
Try use
```yaml
dubbo:
  application:
    parameter[key]: val
```
