### ISSUE TITLE
启动一直报这个无法获取metadata的错误

### ISSUE THREAD

**Issue by zhouyu00** [apache/dubbo#11226]
- [ ] I have searched the [issues](https://github.com/apache/dubbo/issues) of this repository and believe that this is not a duplicate.

## Ask your question here
dubbo:3.1.1
jdk:11
os: centOS 7.6
配置如下:
```
dubbo:
  application:
    name: 
    metadata-service-protocol: tri
  registry:
    address: ${NACOS_REGISTER_ADDR}
    group: ${DUBBO_REGISTER_GROUP}
    parameters:
      namespace: ${NACOS_NAMESPACE}
    username: ${NACOS_USERNAME}
    password: ${NACOS_PASSWORD}
  metadata-report:
    address: ${NACOS_REGISTER_ADDR}
  protocol:
    name: ${DUBBO_PROTOCAL_NAME}
    port: ${DUBBO_PROTOCAL_PORT}
    accesslog: false
  consumer:
    filter: dubboFilterConsumer
    check: false
    timeout: ${DUBBO_CONSUMER_TIMEOUT}
    retries: ${DUBBO_CONSUMER_RETRIES}
  provider:
    filter: dubboFilterProvider

```
代码里面同时使用了rest和 tri 两种协议，直接注解在接口配置上
启动时一直滚动报下面这个错误，

```
[DUBBO] Failed to get app metadata for revision 3005bae31919d143caf981fc3d373483 for type local from instance 10.70.33.251:9092, dubbo version: 3.1.1, current host: 10.70.34.222 org.apache.dubbo.rpc.RpcException: Fail to invoke remote method: getMetadataInfo, provider: tri://10.70.33.251:50051/org.apache.dubbo.metadata.MetadataService?connections=1&corethreads=2&dubbo=2.0.2&group=demoGroup&port=50051&protocol=tri&release=3.1.1&retries=0&side=provider&threadpool=cached&threads=100&timeout=5000&token=**************************************************, cause: org.apache.dubbo.rpc.StatusRpcException: UNKNOWN : unknown ~~ java.lang.NullPointerException ~~  ~~ RemoteAddress:10.70.33.251:50051 ~~         at org.apache.dubbo.rpc.protocol.AbstractInvoker.waitForResultIfSync(AbstractInvoker.java:282) ~~       at org.apache.dubbo.rpc.protocol.AbstractInvoker.invoke(AbstractInvoker.java:185) ~~    at org.apache.dubbo.rpc.listener.ListenerInvokerWrapper.invoke(ListenerInvokerWrapper.java:70) ~~       at org.apache.dubbo.rpc.proxy.InvocationUtil.invoke(InvocationUtil.java:55) ~~  at org.apache.dubbo.rpc.proxy.InvokerInvocationHandler.invoke(InvokerInvocationHandler.java:75) ~~      at org.apache.dubbo.metadata.MetadataServiceDubboProxy0.getMetadataInfo(MetadataServiceDubboProxy0.java) ~~     at org.apache.dubbo.registry.client.metadata.MetadataUtils.getRemoteMetadata(MetadataUtils.java:171) ~~         at org.apache.dubbo.registry.client.AbstractServiceDiscovery.getRemoteMetadata(AbstractServiceDiscovery.java:178) ~~    at org.apache.dubbo.registry.client.event.listener.ServiceInstancesChangedListener.lambda$doOnEvent$2(ServiceInstancesChangedListener.java:158) ~~      at java.base/java.util.Optional.orElseGet(Optional.java:369) ~~         at org.apache.dubbo.registry.client.event.listener.ServiceInstancesChangedListener.doOnEvent(ServiceInstancesChangedListener.java:158) ~~       at org.apache.dubbo.registry.client.event.listener.ServiceInstancesChangedListener.onEvent(ServiceInstancesChangedListener.java:112) ~~         at org.apache.dubbo.registry.client.event.listener.ServiceInstancesChangedListener$AddressRefreshRetryTask.run(ServiceInstancesChangedListener.java:488) ~~     at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) ~~         at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264) ~~        at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304) ~~  at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~~         at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~~         at java.base/java.lang.Thread.run(Thread.java:829) ~~ Caused by: java.util.concurrent.ExecutionException: org.apache.dubbo.rpc.StatusRpcException: UNKNOWN : unknown ~~ java.lang.NullPointerException ~~  ~~ RemoteAddress:10.70.33.251:50051 ~~       at java.base/java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:395) ~~    at java.base/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2022) ~~        at org.apache.dubbo.rpc.AsyncRpcResult.get(AsyncRpcResult.java:195) ~~   at org.apache.dubbo.rpc.protocol.AbstractInvoker.waitForResultIfSync(AbstractInvoker.java:264) ~~       ... 18 more ~~ Caused by: org.apache.dubbo.rpc.StatusRpcException: UNKNOWN : unknown ~~ java.lang.NullPointerException ~~  ~~ RemoteAddress:10.70.33.251:50051 ~~       at org.apache.dubbo.rpc.TriRpcStatus.asException(TriRpcStatus.java:214) ~~      at org.apache.dubbo.rpc.protocol.tri.DeadlineFuture.doReceived(DeadlineFuture.java:134) ~~     at org.apache.dubbo.rpc.protocol.tri.DeadlineFuture.lambda$received$0(DeadlineFuture.java:91) ~~        at org.apache.dubbo.common.threadpool.ThreadlessExecutor$RunnableWrapper.run(ThreadlessExecutor.java:184) ~~     at org.apache.dubbo.common.threadpool.ThreadlessExecutor.waitAndDrain(ThreadlessExecutor.java:103) ~~   at org.apache.dubbo.rpc.AsyncRpcResult.get(AsyncRpcResult.java:193) ~~  ... 19 more
```
