### ISSUE TITLE
[3.0] 如何通过环境变量修改dubbo在zk注册中心的rootPath值

### ISSUE THREAD

**Issue by YuWan1117** [apache/dubbo#11230]
DubboVersion：3.0.12
注册中心：zookeeper

由于`hello-service`模块既提供一个`SpringCloud`接口又提供`Dubbo`接口，并且两者的注册信息在ZK上均会写入`/services`路径下。
希望可以修改`Dubbo`的注册信息写入一个自定义的路径下和`SpringCloud`的进行隔离，了解到`Dubbo`可以通过`dubbo.registry.parameters.rootPath`来进行设置。
想了解下是否可以通过**系统环境变量**来实现这个字段的设置？
目的是避免在每一个项目中的配置中设置此字段，通过系统环境可以进行全局的统一设置。

``` Yaml
dubbo:
  application:
    name: hello-service
  protocol:
    name: tri
    port: 20415
    threads: 500
  registry:
    address: 127.0.0.1:2181
    protocol: zookeeper
    parameters:
     rootPath: demo
  scan:
    base-packages: org.example.hello.service
  config:
    multiple: false
  consumer:
    timeout: 2000
    check: false
```

辛苦社区同学解答，感谢～
