### ISSUE TITLE
When it cannot be serialized, it should give a friendly prompt instead of reporting an error

### ISSUE THREAD

**Issue by wxbty** [apache/dubbo#11268]
### Environment

* Dubbo version: provider=3.2.0-beta.4-SNAPSHOT   consumer=2.7.18
* Operating System version: mac m1
* Java version: 1.8

### Steps to reproduce this issue

1. Create provider and consumer projects, as follows：
   provider:

```xml
   <properties>
        <spring-boot.version>2.3.0.RELEASE</spring-boot.version>
        <dubbo.version>3.2.0-beta.4-SNAPSHOT</dubbo.version>
    </properties>
```

```yaml
dubbo:
  application:
    name: sp-provider
  registry:
    address: zookeeper://127.0.0.1:2181
  protocol:
    port: 20881
```

   ```java
   @DubboService
   public class GameServiceImpl implements GameService {
       public String play(String name) {
           return "hello 2181:"+name;
       }
   }
   ```

   consumer:

   ```xml
   <properties>
        <spring-boot.version>2.3.0.RELEASE</spring-boot.version>
        <dubbo.version>2.7.18</dubbo.version>
    </properties>
   ```

```yaml
dubbo:
  application:
    name: sp-consumer
  registry:
    address: zookeeper://127.0.0.1:2181
```

```java
@DubboReference
private GameService gameService;


 public static void main(String[] args) {
        ConfigurableApplicationContext context = SpringApplication.run(ConsumerApplication.class, args);
        ConsumerApplication bean =  (ConsumerApplication) context.getBean("consumerApplication");
        System.out.println(bean.play());
    }

    public String play() {
        return gameService.play("feiguohai");
    }
```

2. run main func

### Expected Behavior

call successfully 

### Actual Behavior

call successfully ,  but every 60s,   NPE will be reported

If there is an exception, please attach the exception trace:

![image](https://user-images.githubusercontent.com/38374721/211478151-f3dca220-f519-4254-8d2c-3bcedf962974.png)

**Comment by wxbty** [comment]
The troubleshooting found that the default serialization method was modified in 3.2, hession2->fastjson2, and the consumer of 2.7.18 could not find the corresponding serialization method for the returned heartbeat request. Finally, it can be solved by modifying the provider-side serialization method, as follows:

```yaml
dubbo:
  application:
    name: sp-provider
  registry:
    address: zookeeper://127.0.0.1:2181
  protocol:
    port: 20881
  provider:
    serialization: hessian2
```

see  https://cn.dubbo.apache.org/zh/docs3-v2/java-sdk/upgrades-and-compatibility/serialization-upgrade/

I think the error message should be more friendly.
