### ISSUE TITLE
动态配置在重启后不生效

### ISSUE THREAD

**Issue by sadlay** [apache/dubbo#11874]
- [x] I have searched the [issues](https://github.com/apache/dubbo/issues) of this repository and believe that this is not a duplicate.

### Environment

* Dubbo version: 3.1.1
* Operating System version: MacOS
* Java version: 1.8

### Steps to reproduce this issue

1. 新增动态配置

   **Data ID**: cn.sadlay.dubbo.apple.api.AppleService:1.0.0:generic.configurators

   **Group**: dubbo

   ```yaml
   configVersion: v3.1
   scope: service
   key: cn.sadlay.dubbo.apple.api.AppleService
   enabled: true
   configs:
   - addresses: [0.0.0.0]
     side: consumer
     parameters:
       loadbalance: consistenthash
   ```

2. 重启 **Consumer**

3. 调用 **AppleService**，还是使用默认的轮训策略 **RandomLoadBalance** 

4. 更新动态配置（添加换行，不更新具体内容）， **ConsistentHashLoadBalance** 生效

### Expected Behavior

重启后服务调用使用 **ConsistentHashLoadBalance** 负载均衡策略

### Actual Behavior

重启后服务调用使用默认 **RandomLoadBalance** 负载均衡策略，动态配置失效
