### ISSUE TITLE
Dubbo整合Nacos启动自动关闭，无任何报错信息

### ISSUE THREAD

**Issue by orange-coders** [apache/dubbo#12106]
### Environment

* Dubbo version: 3.20
* Operating System version: Windows11
* Java version: 17

父模块POM文件
```
 <properties>
        <maven.compiler.source>17</maven.compiler.source>
        <maven.compiler.target>17</maven.compiler.target>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <spring-cloud.version>2022.0.2</spring-cloud.version>
        <spring-cloud-alibaba.version>2022.0.0.0-RC1</spring-cloud-alibaba.version>
        <spring-boot.version>3.0.5</spring-boot.version>

    </properties>

    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-dependencies</artifactId>
                <version>${spring-boot.version}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>

            <dependency>
                <groupId>org.springframework.cloud</groupId>
                <artifactId>spring-cloud-dependencies</artifactId>
                <version>${spring-cloud.version}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>

            <dependency>
                <groupId>com.alibaba.cloud</groupId>
                <artifactId>spring-cloud-alibaba-dependencies</artifactId>
                <version>${spring-cloud-alibaba.version}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
        </dependencies>
    </dependencyManagement>
```
生产者POM文件：
```
   <dependencies>
        <!-- SpringCloud Alibaba Nacos -->
        <dependency>
            <groupId>com.alibaba.cloud</groupId>
            <artifactId>spring-cloud-starter-alibaba-nacos-discovery</artifactId>
        </dependency>

        <!-- SpringCloud Alibaba Nacos Config -->
        <dependency>
            <groupId>com.alibaba.cloud</groupId>
            <artifactId>spring-cloud-starter-alibaba-nacos-config</artifactId>
        </dependency>

        <dependency>
            <groupId>org.apache.dubbo</groupId>
            <artifactId>dubbo-spring-boot-starter</artifactId>
            <version>3.2.0</version>
        </dependency>


        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter</artifactId>
        </dependency>
    </dependencies>
```

生产者配置：
``` yaml
server:
  port: 8000
spring:
  application:
    name: producer-service
  cloud:
    nacos:
      server-addr: 192.168.31.195:8848
      username: nacos
      password: nacos

dubbo:
  application:
    name: producer-service-dubbo
  registry:
    address: nacos://192.168.31.195:8848
    username: nacos
    password: nacos
    check: false
  protocol:
    name: dubbo
    port: -1
```
启动生产者时控制台没有任何错误信息，但是生产者会自动关闭。
下面是控制台的截图：
![image](https://user-images.githubusercontent.com/58932259/232298882-9bff123c-23a1-4c16-86d2-2d788e8d5410.png)
