### ISSUE TITLE
NullPointException when requesting MetadataService on a injected Spring bean custom filter 

### ISSUE THREAD

**Issue by NikoTung** [apache/dubbo#12122]
- [x] I have searched the [issues](https://github.com/apache/dubbo/issues) of this repository and believe that this is not a duplicate.

### Environment

* Dubbo version: 3.2.0
* Operating System version: Mac OS
* Java version: 17

### Steps to reproduce this issue

I created a [demo](https://github.com/NikoTung/dubbo3-issue) to reproduce the issue.

While I tried to fix this issue  #12078 , I found a `NullPointException` when the consumer start up and request to `org.apache.dubbo.registry.client.metadata.MetadataServiceDelegation#getMetadataInfo` service in the custom filter which injected a Spring bean successfully. This `NullPointException` only happen when request to the `MetadataService`, the other requests don't affect. It since likes there are two custom filter instances created for the same type.

And I also found the consumer doesn't register to nacos with the following config, can't find the consumer instance on the nacos console.

```
  dubbo:
  application:
    name: service-consumer-dubbo
    register-mode: instance
    service-discovery:
      migration: FORCE_APPLICATION
    parameters:
      register-consumer-url: true
    qos-enable: false
    register-consumer: true
```

### Expected Behavior

* No exception for the MetadataService request.
* Dubbo consumer register to Nacos

### Actual Behavior

* NullPointException occurred in custom filter injected with Spring bean for `MetadataService`.
* Can't find Dubbo consumer in Nacos console.

**Comment by AlbumenJ** [comment]
Do you mean that you want to inject `MetadataService` into your bean?

**Comment by AlbumenJ** [comment]
There are two Filter instance for MetadataService (Internal Services) and user-define services. Filter for internal serivces is useless and you can ignore it.

**Comment by NikoTung** [comment]
Thanks, now I know that the user-define Filter would be instanced twice, for Internal Services and User-define Services. But I think the Filter should work exactly in both Internal Service and User-define Services, in my case, the Filter instance for Internal Service(MetadataService) was not injected a Spring bean via `public void setBeanToInject(BeanToInject beanToInject)` method which caused a `NullPointException`.

**Comment by AlbumenJ** [comment]
The reason is that spring context is on Dubbo module model level.

**Comment by NikoTung** [comment]
Ok. So now my question is how can I avoid or fix this `NullPointException`? Or it's not a good idea to inject Spring bean in Dubbo3 via a `setter` method?

**Comment by AlbumenJ** [comment]
> Or it's not a good idea to inject Spring bean in Dubbo3 via a `setter` method?

It would be better to create a `Factory` class for yourself.

**Comment by NikoTung** [comment]
Thanks. I think it would be great to write this in docs,like:
* Injecting a Spring bean is not suggested.
* Recommend to use a Factory class because ...
* ...

**Comment by NikoTung** [comment]
For the question "Dubbo consumer not register to Nacos", can you @AlbumenJ help to check. Here is the configuration:
```
 dubbo:
  application:
    name: service-consumer-dubbo
    register-mode: instance
    service-discovery:
      migration: FORCE_APPLICATION
    parameters:
      register-consumer-url: true
    qos-enable: false
    register-consumer: true
  registry:
    address: nacos://127.0.0.1:8848
    parameters:
      register-consumer-url: true
```
> Dubbo3.0.0版本以后，增加了是否注册消费者的参数，如果需要将消费者注册到nacos注册中心上，需要将参数(register-consumer-url)设置为true，默认是false。

From the [docs](https://cn.dubbo.apache.org/zh-cn/overview/mannual/java-sdk/reference-manual/registry/nacos/).
I specified the `register-consumer-url` to `true`, but still can't find the consumer in Nacos console.
