### ISSUE TITLE
dubbo3.2+nacos2.1.2, consumer failed to get metadata -> throw RPCExpection

### ISSUE THREAD

**Issue by QAQdev** [apache/dubbo#12155]
<img width="1568" alt="image" src="https://user-images.githubusercontent.com/73159641/233545759-34202cc2-02f3-4b7a-a6bc-8d2986c67a54.png">
<img width="1569" alt="image" src="https://user-images.githubusercontent.com/73159641/233545775-3f8bff9d-94d2-4ce2-a97e-cec2a83ee253.png">

provider可以在正常在nacos上显示注册信息，consumer启动后则一直获取不到metadata，希望得到解答！

**Comment by songxiaosheng** [comment]
> <img width="1568" alt="image" src="https://user-images.githubusercontent.com/73159641/233545759-34202cc2-02f3-4b7a-a6bc-8d2986c67a54.png">
> <img width="1569" alt="image" src="https://user-images.githubusercontent.com/73159641/233545775-3f8bff9d-94d2-4ce2-a97e-cec2a83ee253.png">
> 
> provider可以在正常在nacos上显示注册信息，consumer启动后则一直获取不到metadata，希望得到解答！

This is a timeout issue. Is there any network connectivity? You can try telnet IP port

**Comment by QAQdev** [comment]
> yes, I tried `ping 10.251.1.1` and `telnet 10.251.1.1 20880` and both of them show the network is connective. I think `10.251.1.1` should be the address that provider runs at?

**Comment by songxiaosheng** [comment]
> > yes, I tried `ping 10.251.1.1` and `telnet 10.251.1.1 20880` and both of them show the network is connective. I think `10.251.1.1` should be the address that provider runs at?
> 
> 

Yes, this metadata service is an internal service provided by the provider

**Comment by QAQdev** [comment]
> 

So what may the issue lies? I tried many times and the consumer is always timeout. This is the details of the console log:
```
2023-04-21 16:46:32.998  INFO 3810 --- [ternal.notifier] o.a.d.r.client.ServiceDiscoveryRegistry  :  [DUBBO] Trying to subscribe from apps dubbo-nacos-demo-provider for service key dubbo.nacos.demo.DemoService:1.0.0, , dubbo version: 3.2.0, current host: 10.251.1.1
2023-04-21 16:47:02.938  WARN 3810 --- [           main] o.a.d.r.proxy.InvokerInvocationHandler   :  [DUBBO] [Dubbo-Consumer] execute service dubbo-nacos-demo-provider/org.apache.dubbo.metadata.MetadataService:1.0.0:dubbo#getMetadataInfo cost 30043.098750 ms, this invocation almost (maybe already) timeout. Timeout: 30000ms
invocation context:
path=org.apache.dubbo.metadata.MetadataService;
version=1.0.0;
timeout=30000;
group=dubbo-nacos-demo-provider;
thread info: 
Start time: 3160144039375
+-[ Offset: 0.000000ms; Usage: 30043.098750ms, 100% ] Receive request. Client invoke begin. ServiceKey: dubbo-nacos-demo-provider/org.apache.dubbo.metadata.MetadataService:1.0.0 MethodName:getMetadataInfo, dubbo version: 3.2.0, current host: 10.251.1.1, error code: 3-4. This may be caused by , go to https://dubbo.apache.org/faq/3/4 to find instructions. 
2023-04-21 16:47:02.938  INFO 3810 --- [           main] o.a.d.r.transport.netty4.NettyChannel    :  [DUBBO] Close netty channel [id: 0xa8cdc6e2, L:/10.251.1.1:53568 - R:/10.251.1.1:20881], dubbo version: 3.2.0, current host: 10.251.1.1
2023-04-21 16:47:02.947 ERROR 3810 --- [           main] o.a.d.r.client.metadata.MetadataUtils    :  [DUBBO] Failed to get app metadata for revision f743357fb13b2e782837efbb8809eedc for type local from instance 10.251.1.1:20880, dubbo version: 3.2.0, current host: 10.251.1.1, error code: 1-39. This may be caused by , go to https://dubbo.apache.org/faq/1/39 to find instructions. 
```

**Comment by songxiaosheng** [comment]
> > 
> 
> So where may the issue lies? I tried many times and the consumer is always timeout. This is the detail of the console log:
> ```
> 2023-04-21 16:46:32.998  INFO 3810 --- [ternal.notifier] o.a.d.r.client.ServiceDiscoveryRegistry  :  [DUBBO] Trying to subscribe from apps dubbo-nacos-demo-provider for service key dubbo.nacos.demo.DemoService:1.0.0, , dubbo version: 3.2.0, current host: 10.251.1.1
> 2023-04-21 16:47:02.938  WARN 3810 --- [           main] o.a.d.r.proxy.InvokerInvocationHandler   :  [DUBBO] [Dubbo-Consumer] execute service dubbo-nacos-demo-provider/org.apache.dubbo.metadata.MetadataService:1.0.0:dubbo#getMetadataInfo cost 30043.098750 ms, this invocation almost (maybe already) timeout. Timeout: 30000ms
> invocation context:
> path=org.apache.dubbo.metadata.MetadataService;
> version=1.0.0;
> timeout=30000;
> group=dubbo-nacos-demo-provider;
> thread info: 
> Start time: 3160144039375
> +-[ Offset: 0.000000ms; Usage: 30043.098750ms, 100% ] Receive request. Client invoke begin. ServiceKey: dubbo-nacos-demo-provider/org.apache.dubbo.metadata.MetadataService:1.0.0 MethodName:getMetadataInfo, dubbo version: 3.2.0, current host: 10.251.1.1, error code: 3-4. This may be caused by , go to https://dubbo.apache.org/faq/3/4 to find instructions. 
> 2023-04-21 16:47:02.938  INFO 3810 --- [           main] o.a.d.r.transport.netty4.NettyChannel    :  [DUBBO] Close netty channel [id: 0xa8cdc6e2, L:/10.251.1.1:53568 - R:/10.251.1.1:20881], dubbo version: 3.2.0, current host: 10.251.1.1
> 2023-04-21 16:47:02.947 ERROR 3810 --- [           main] o.a.d.r.client.metadata.MetadataUtils    :  [DUBBO] Failed to get app metadata for revision f743357fb13b2e782837efbb8809eedc for type local from instance 10.251.1.1:20880, dubbo version: 3.2.0, current host: 10.251.1.1, error code: 1-39. This may be caused by , go to https://dubbo.apache.org/faq/1/39 to find instructions. 
> ```
> Then consumer throws `RPCExecption` indicating that invocation is timeout

Confirm if the provider has received the request

**Comment by QAQdev** [comment]
> 

I refer to https://cn.dubbo.apache.org/zh-cn/overview/mannual/java-sdk/reference-manual/metadata-center/nacos/ and configure `metadata-type: remote`, then the cosumer doesn't throw `RPCExpection`.
> I make cosumer a `RestController` and call it throw `127.0.0.1/hello`
But I notice there is no log (**i.e. request info you mentioned**) at provider side, while consumer side's log is:
```
invocation context:
path=dubbo.nacos.demo.DemoService;
remote.application=dubbo-nacos-demo-consumer;
interface=dubbo.nacos.demo.DemoService;
version=1.0.0;
timeout=3000;
thread info: 
Start time: 6058177882625
+-[ Offset: 0.000000ms; Usage: 9082.774666ms, 100% ] Receive request. Client invoke begin. ServiceKey: dubbo.nacos.demo.DemoService:1.0.0 MethodName:sayHello
  +-[ Offset: 5.083916ms; Usage: 3017.671667ms, 33% ] Invoker invoke. Target Address: 10.251.1.1:20880
  +-[ Offset: 3023.084250ms; Usage: 3030.060500ms, 33% ] Invoker invoke. Target Address: 10.251.1.1:20880
  +-[ Offset: 6053.512583ms; Usage: 3028.777667ms, 33% ] Invoker invoke. Target Address: 10.251.1.1:20880, dubbo version: 3.2.0, current host: 10.251.1.1, error code: 3-4. This may be caused by , go to https://dubbo.apache.org/faq/3/4 to find instructions. 
2023-04-21 17:35:41.147 ERROR 4704 --- [nio-8889-exec-1] o.a.c.c.C.[.[.[/].[dispatcherServlet]    : Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request processing failed; nested exception is org.apache.dubbo.rpc.RpcException: Failed to invoke the method sayHello in the service dubbo.nacos.demo.DemoService. Tried 3 times of the providers [10.251.1.1:20880] (1/1) from the registry 172.17.0.13:8848 on the consumer 10.251.1.1 using the dubbo version 3.2.0. Last error is: Invoke remote method timeout. method: sayHello, provider: DefaultServiceInstance{serviceName='dubbo-nacos-demo-provider', host='10.251.1.1', port=20880, enabled=true, healthy=true, metadata={dubbo.endpoints=[{"port":20880,"protocol":"dubbo"}], dubbo.metadata.revision=9b326a1e762e969a10c006bea5ed6a02, dubbo.metadata.storage-type=remote, timestamp=1682069664033}}, service{name='dubbo.nacos.demo.DemoService',group='null',version='1.0.0',protocol='dubbo',port='20880',params={executor-management-mode=isolation, side=provider, file-cache=true, release=3.2.0, methods=sayHello, deprecated=false, dubbo=2.0.2, interface=dubbo.nacos.demo.DemoService, service-name-mapping=true, version=1.0.0, timeout=5000, generic=false, revision=1.0.0, metadata-type=remote, application=dubbo-nacos-demo-provider, prefer.serialization=fastjson2,hessian2, background=false, dynamic=true, anyhost=true},}, cause: org.apache.dubbo.remoting.TimeoutException: Waiting server-side response timeout by scan timer. start time: 2023-04-21 17:35:38.101, end time: 2023-04-21 17:35:41.128, client elapsed: 2 ms, server elapsed: 3025 ms, timeout: 3000 ms, request: Request [id=5, version=2.0.2, twoWay=true, event=false, broken=false, mPayload=0, data=null], channel: /10.251.1.1:56535 -> /10.251.1.1:20880] with root cause
```
Then consumer throws `org.apache.dubbo.remoting.TimeoutException: Waiting server-side response timeout by scan timer`
It's weird, Then I checked the nacos:
<img width="1032" alt="image" src="https://user-images.githubusercontent.com/73159641/233603889-8ad746cf-b28b-4216-88fa-59d94d5bc260.png">
The table only contains info of provider, is it normal?

**Comment by songxiaosheng** [comment]
The remote configuration is centralized and does not require RPC. You can manually access this RPC service on the provider's machine through the QoS tool to see if the provider's interface is working properly

**Comment by QAQdev** [comment]
> The remote configuration is centralized and does not require RPC. You can manually access this RPC service on the provider's machine through the QoS tool to see if the provider's interface is working properly

Fine, but if I remove `metadata-type: remote`, consumer side will fail to get metadata, which returns to the very first state. can you tell me how to confirm if the provider has received the request? The current situation is:
1. ping and telnet show the network is fine
2. nacos console shows the provider is registered
3. consumer fails to get metadata and therefore throws RPCExpection
Can you show me the possible solution more clearly? I have been configuring for nearly one day...

**Comment by QAQdev** [comment]
…Found a not so elegant way to solve this issue, `10.251.1.1` may be an address that generated by nacos which consumer cannot access (though `ping` and `telnet` show no problem).
In IDEA, you can `Edit Configurations -> Modify Options -> Add VM Options`, then add `-DDUBBO_IP_TO_REGISTRY=[YOUR_PC_IP]`
![image](https://user-images.githubusercontent.com/73159641/233627579-f5f59823-af84-4ccc-9201-c5e6e3f520b9.png)

**Comment by sunshineYao805** [comment]
我也碰到了这个问题，我的consumer服务里依赖了好几个不同的provider服务，只用一个provider的service出现了Failed to get app metadata的错误。看你最后的解决办法，这个问题看起来像是provider端没有上报元数据或者上报元数据失败导致的？

**Comment by QAQdev** [comment]
> 我也碰到了这个问题，我的consumer服务里依赖了好几个不同的provider服务，只用一个provider的service出现了Failed to get app metadata的错误。看你最后的解决办法，这个问题看起来像是provider端没有上报元数据或者上报元数据失败导致的？

yes, i thought it may relate to the reason i pointed out

**Comment by xiaolinstar** [comment]
我遇到了相同的问题，以容器docker的方式启动无法找到provider，但在宿主机上直接启动jar包连接成长。
操作系统：arm64 macOS 15.0
Docker: 26.0
Nacos: 2022.0.0.0
Dubbo: 3.2.0
项目中微服务auth是provider，gateway是consumer，报错rpc找不到metadata。
Docker-Compose启动脚本如下：
```yaml
# 创建网桥
networks:
  magic-network:
    external: false

services:
  magic-nacos:
    image: nacos/nacos-server:v2.4.0
    container_name: magic-local-nacos
    hostname: magic-local-nacos
    ports:
      - "8848:8848"
      - "9848:9848" # 必须添加，否则无法正常使用
      - "9849:9849"
    networks:
      - magic-network
    restart: no
    environment:
      MODE: standalone
    volumes:
      - /etc/timezone:/etc/timezone
      - /etc/localtime:/etc/localtime

  magic-mysql:
    # 业务数据库
    image: mysql:8.4
    container_name: magic-local-mysql
    hostname: magic-local-mysql
    ports:
      - "3306:3306"
    networks:
      - magic-network
    environment:
      LANG: C.UTF-8 # 中文乱码-1
      # 数据库密码
      MYSQL_ROOT_PASSWORD: 123456
    volumes:
      - ./static/mysql:/docker-entrypoint-initdb.d/
    # 中文乱码-2
    command: ['--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci' ]

  magic-auth-redis:
    # 鉴权中间件redis
    image: redis:7.4-alpine
    container_name: magic-local-auth-redis
    hostname: magic-local-auth-redis
    restart: no
    ports:
      - "6379:6379"
    networks:
      - magic-network

  magic-rabbitmq:
    image: rabbitmq:3-management
    container_name: magic-local-rabbitmq
    hostname: magic-local-rabbitmq
    restart: no
    environment:
      RABBITMQ_DEFAULT_USER: xiaolin
      RABBITMQ_DEFAULT_PASS: 123456rabbit
      RABBITMQ_DEFAULT_VHOST: /local-media
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - magic-network

  magic-auth:
    image: xxl1997/magic-video:auth-0.0.1-SNAPSHOT
    container_name: magic-local-auth
#    build:
#      context: ./auth
#      dockerfile: Dockerfile
    hostname: magic-local-auth
    restart: no
    ports:
      - "8999:8999"
    networks:
      - magic-network
    depends_on:
      - magic-nacos
      - magic-mysql
      - magic-rabbitmq
      - magic-auth-redis

  magic-gateway:
    image: xxl1997/magic-video:gateway-0.0.1-SNAPSHOT
    container_name: magic-local-gateway
#    build:
#      context: ./gateway
#      dockerfile: Dockerfile
    hostname: magic-local-gateway
    restart: no
    ports:
      - "9001:9001"
    networks:
      - magic-network
    depends_on:
      - magic-auth
#
#  net_test:
#    image: alpine
#    container_name: net_test_container
#    depends_on:
#      - magic-auth
#    networks:
#      - magic-network
#    command: /bin/sh -c "while true; do sleep 3600; done"
````
