### ISSUE TITLE
多注册中心情况下添加group，拓展cluster找不到invoker's url中的对应元数据

### ISSUE THREAD

**Issue by InscienceMan** [apache/dubbo#12325]
dubbo:3.1.8
jdk:8
zookeeper：3.7.1

provider的Dubbo配置：
```
dubbo:
 registries:
    zonea:
      address: zookeeper://localhost:2182
      group: gray
    zoneb:
      address: zookeeper://localhost:2183
      group: gray
```

comsumer的Dubbo配置：
```
dubbo:
 registries:
    zonea:
      address: zookeeper://localhost:2182
      cluster: xxxcluster
      group: gray
    zoneb:
      address: zookeeper://localhost:2183
      cluster: xxxcluster
      group: gray
```
在provider的register指定了group，注册在zookeeper的信息都以/gray开头。但在暴露元数据信息时，serviceKey还是不带/gray的。在consumer自定义的cluster中去获取invoker的parameter，无法正常找到，因为consumer调用中认为serviceKey是带/gray的

![image](https://github.com/apache/dubbo/assets/96465416/7becdaab-d473-442b-904f-7c49f93a2bdf)
