### ISSUE TITLE
dubbo-spring-boot-tracing-otel-zipkin-starter 配置未生效

### ISSUE THREAD

**Issue by OnceCrazyer** [apache/dubbo#12345]
项目：
  spring boot 3.0.5  + jdk 17 + dubbo 3.2.1 ,日志：spring-boot-starter-log4j2
按照官网进行配置，日志中打印traceId,spanId都为空
控制台输出如下：
[2023-05-18 18:20:34:125] [INFO] - org.apache.dubbo.common.logger.log4j2.Log4j2Logger.info(Log4j2Logger.java:61) - [,]（此处应为traceId 与 spanId） -

**Comment by songxiaosheng** [comment]
你们日志MDC怎么配置的
```
logging:
  level:
    root: info
  pattern:
    console: '[%d{dd/MM/yy HH:mm:ss:SSS z}] %t %5p %c{2} [%X{traceId:-}, %X{spanId:-}]: %m%n'

```
