### ISSUE TITLE
Dubbo3 + grpc 远程调用的参数和结果均为空

### ISSUE THREAD

**Issue by TremblingV5** [apache/dubbo#12459]
- [x] I have searched the [issues](https://github.com/apache/dubbo/issues) of this repository and believe that this is not a duplicate.

### Environment

* Dubbo version: 3.2.2 & 3.2.0
* Operating System version: Windows 11
* Java version: JDK 17

### Steps to reproduce this issue

github url for this issue: https://github.com/TremblingV5/dubbo-grpc-demo

我使用Dubbo3和grpc尝试搭建一个简单的demo，主要依赖库的版本信息如下：

```xml
<dubbo.version>3.2.2</dubbo.version>
<springboot.version>2.7.8</springboot.version>
<protoc.version>3.7.1</protoc.version>
<grpc.version>1.55.1</grpc.version>
```

这个demo已经上传到了github，上方链接即这个demo的链接。我调用相关接口，获取远程调用的结果，发现是空字符串；使用Idea打断点debug发现，一开始构建的请求体和返回体是正常的，但是经过远程调用后全部变为了空，怀疑可能是序列化的问题？

demo的配置文件如下：

```yml
dubbo:
  application:
    name: Consumer
  registry:
    address: nacos://localhost:8848
  consumer:
    check: false
  protocol:
    name: dubbo
    host: 127.0.0.1
    port: 12346

server:
  port: 9090
```

```yml
dubbo:
  protocol:
    name: dubbo
    host: 127.0.0.1
    port: 12345
  application:
    name: Producer
  registry:
    address: nacos://localhost:8848
```

发生这个问题时，控制台没有输出任何日志信息。
