### ISSUE TITLE
多注册中心 key 覆盖问题

### ISSUE THREAD

**Issue by ooooo-youwillsee** [apache/dubbo#12629]
- [ ] I have searched the [issues](https://github.com/apache/dubbo/issues) of this repository and believe that this is not a duplicate.

### Environment

* Dubbo version: 3.1.10
* Operating System version: macos
* Java version: 1.8

### Steps to reproduce this issue

配置如下
```
dubbo:
  application:
    parameters:
      registry-type: service
  registries:
    a:
      address: nacos://172.16.1.104:7848
      group: DUBBO_SERVICE_GROUP
      parameters:
        namespace: a
    b:
      address: nacos://172.16.1.104:7848
      group: DUBBO_SERVICE_GROUP
      parameters:
        namespace: b
```

Pls. provide [GitHub address] to reproduce this issue.

### Expected Behavior

可以注册到两个命名空间中

### Actual Behavior

只会注册到一个命名空间中

If there is an exception, please attach the exception trace:

我调试了一下，发现 key 是相同的
代码位置： `org.apache.dubbo.registry.support.AbstractRegistryFactory#getRegistry`,
注意这里的 this 实例，对于两个注册中心，生成key都是一样的。
![image](https://github.com/apache/dubbo/assets/30012389/9a950a4f-f408-4b1c-9341-339249d90498)

```

```
