### ISSUE TITLE
consumer multiple registries in triple protocol cause service not found

### ISSUE THREAD

**Issue by iJIAJIA** [apache/dubbo#12709]
- [x] I have searched the [issues](https://github.com/apache/dubbo/issues) of this repository and believe that this is not a duplicate.

### Environment

* Dubbo version: 3.2.x
* Operating System version: linux
* Java version: 1.8

### Steps to reproduce this issue

1. consumer配置多注册中心(这里用的nacos) , 服务发现使用APPLICATION_FIRST(默认值) 或者 FORCE_APPLICATION
``` yaml
dubbo:
    registries:
      default:
        parameters:
          namespace: ${nacos.namespace2}
        address: nacos://${nacos.server-addr2}?username=${nacos.username:}&password=${nacos.password:}
        # nacos注册中心需要配置group,这里为默认
        group: DEFAULT_GROUP
        subscribe: true
        check: false
    foo:
      parameters:
        namespace: ${nacos.namespace}
      address: nacos://${nacos.server-addr}?username=${nacos.username:}&password=${nacos.password:}
      # nacos注册中心需要配置group,这里为默认
      group: DEFAULT_GROUP
      subscribe: true
      check: false
```
2. 服务与服务之间使用triple协议
3. provider 启用应用注册或者双注册模式
```yaml
dubbo:
  application:
    register-mode: all
```

Pls. provide [GitHub address] to reproduce this issue.

### Expected Behavior

期望调用成功
### Actual Behavior
consumer侧报 service not found

原因:
Triple协议通过 grpc header里的 serviceName + version + group来做唯一路径标识.  (注意这里的group为@DubboService里的group,不是注册中心的group.)
consumer触发调用时, RequestMetadata#toHeaders里会将consumerUrl里的group作为tri-service-group进行传递. 正常情况这里应该没有group才对. 但调用时发现group为DEFAULT_GROUP, 导致路径不匹配. 
```java
RequestMetadata createRequest(MethodDescriptor methodDescriptor, Invocation invocation,
                                  Integer timeout) {
       ...
        final RequestMetadata meta = new RequestMetadata();
        final URL url = getUrl();
        ...
        meta.group = url.getGroup();
        ...
    }
```
由于客户端服务发现使用了APPLICATION_FIRST,  且能通过ServiceName获取到服务列表. 这里的URL是 org.apache.dubbo.registry.client.InstanceAddressURL, 其group获取逻辑为
```java
@Override
    public String getGroup() {
        return RpcContext.getServiceContext().getGroup();
    }
```

当consumer配置多个registries时, ReferenceConfig#createInvoker时, 会走到多注册中心逻辑
```java
private void createInvoker() {
        if (urls.size() == 1) {
           ...
        } else {
            List<Invoker<?>> invokers = new ArrayList<>();
            URL registryUrl = null;
            for (URL url : urls) {
                // For multi-registry scenarios, it is not checked whether each referInvoker is available.
                // Because this invoker may become available later.
                invokers.add(protocolSPI.refer(interfaceClass, url));

                if (UrlUtils.isRegistry(url)) {
                    // use last registry url
                    registryUrl = url;
                }
            }

            if (registryUrl != null) {
               ..
               //  这里会配置一个StaticDirectory, 并且它的consumerUrl为最后一个注册中心的注册地址, 此时注意到注册中心里是带了group的.
                invoker = Cluster.getCluster(registryUrl.getScopeModel(), cluster, false).join(new StaticDirectory(registryUrl, invokers), false);
            } else {
               ....
            }
        }
```
consumer触发调用时, 会走到 org.apache.dubbo.rpc.proxy.InvocationUtil#invoke 方法, 其中有个逻辑是配置RpcServiceContext里的ConsumerUrl. 源头是从ClusterInvoker里获取.  
```java
public static Object invoke(Invoker<?> invoker, RpcInvocation rpcInvocation) throws Throwable {
        // 此时会去ClusterInvoker里getUrl
        URL url = invoker.getUrl();
        String serviceKey = url.getServiceKey();
        rpcInvocation.setTargetServiceUniqueName(serviceKey);

        // invoker.getUrl() returns consumer url.
        // 这个url实际为上述referenceConfig里的registryUrl, 它是带着group的. 
        RpcServiceContext.getServiceContext().setConsumerUrl(url);

        
    }
```
