### ISSUE TITLE
tri 协议  No provider available for the service

### ISSUE THREAD

**Issue by jzcccc** [apache/dubbo#12900]
dubbo版本：3.2.0
nacos版本：2.1.0

消费端配置：

```
spring:
  application:
    name: boot-consumer
dubbo:
  protocol:
    port: -1
    name: tri
  registry:
    address: nacos://${nacos.server-address}:${nacos.port}/?namespace=${nacos.registry-namespace}&username=${nacos.username}&password=${nacos.password}&registry-type=service
  metadata-report:
    address: nacos://${nacos.server-address}:${nacos.port}/?namespace=${nacos.registry-namespace}&username=${nacos.username}&password=${nacos.password}
  application:
    service-discovery:
      migration: FORCE_APPLICATION # 只消费应用级地址，如无地址则报错，单订阅 3.x 地址
    name: boot-consumer
    metadata-type: remote
  consumer:
    check: false
    protocol: tri
#nacos 配置
nacos:
  server-address: 127.0.0.1
  port: 8848
  username: nacos
  password: nacos
  registry-namespace: dubbo
  metadata-namespace: dubbo-meta
```

服务端配置：
```
dubbo:
  scan:
    base-packages: com.jzcccc.dubbo.provider.service
  protocol:
    name: tri
    port: -1
  registry:
    address: nacos://${nacos.server-address}:${nacos.port}/?namespace=${nacos.registry-namespace}&username=${nacos.username}&password=${nacos.password}&registry-type=service
    parameters:
    - register-mode: instance #应用级别
    metadata-report: #元数据中心
      address: nacos://${nacos.server-address}:${nacos.port}/?namespace=${nacos.metadata-namespace}&username=${nacos.username}&password=${nacos.password}
  application:
    name: boot-provider
    metadata-type: remote
nacos:
  server-address: 127.0.0.1
  port: 8848
  username: nacos
  password: nacos
  registry-namespace: dubbo
  metadata-namespace: dubbo-meta
```
## Ask your question here
服务端启动成功，并且nacos能看到对应的服务，访问http://127.0.0.1:22222/ls也能查到服务。但是客户端访问报错

```
org.apache.dubbo.rpc.RpcException: Failed to invoke the method sayHello in the service com.jzcccc.dubbo.consumer.api.SayHelloService. No provider available for the service com.jzcccc.dubbo.consumer.api.SayHelloService from registry 127.0.0.1:8848 on the consumer 172.26.13.121 using the dubbo version 3.2.0. Please check if the providers have been started and registered.
```
