### ISSUE TITLE
 address cache not build  on the consumer

### ISSUE THREAD

**Issue by syllvin** [apache/dubbo#12956]
```
dubbo.version：3.0.3
nacos-client：2.0.4
nacos-discovery/nacos-config：2021.1
spring.boot：2.5.14
```

dubbo yml配置：
```
dubbo:
  application:
    logger: slf4j
    metadataType: remote
    register-mode: instance
    service-discovery:
      migration: FORCE_APPLICATION
    qos-enable: false

  protocol:
    name: dubbo
    port: -1
  registry:
    address: nacos://127.0.0.1:8848
    group: DUBBO_GROUP
    parameters:
      namespace: 7aeae807-4718-479e-a5f0-fa810feeef0f
    protocol: nacos
    username: nacos
    password: nacos
  metadata-report:
    address: nacos://127.0.0.1:8848
    group: DUBBO_GROUP
    username: nacos
    password: nacos
  consumer:
    cache: false
    validation: true
    timeout: 3000
    check: false
  scan:
    # 接口实现类扫描
    base-packages: club.demo.system.provider
```
