### ISSUE TITLE
dubbo+spring boot支持同时像nacos注册dubbo端口和http端口吗

### ISSUE THREAD

**Issue by luger1990** [apache/dubbo#13182]
我们dubbo是这么用的：
每个服务都是一个spring boot应用+dubbo 服务端。各个服务之前可以通过dubbo协议调用。但是各个服务也通过spring boot内置的tomcat对外提供http服务。 现在往nacos注册的只有dubbo端口，是否可以把http端口也注册进去但是不影响dubbo调用？

我的场景是：
希望同一个服务注册到nacos的dubbo端口供其他dubbo消费者调用，注册到nacos的http端口给网关使用，网关读取nacos配置实现http转发

备用方案：
启动服务的时候注册两个instance到nacos一个是dubbo调用的一个是{service-name}-http 注册http端口，给网关使用。

**Comment by luger1990** [comment]
目前这么解决的，spring boot项目中加了如下配置：
```
spring:
     cloud:
    nacos:
      config:
        import-check:
          enabled: false
      discovery:
        server-addr: @nacos.server@
        metadata:
          protocol: http
        service: ${spring.application.name}-http
```
再加上dubbo的配置就会注册两个instance到nacos 一个是spring-service 一个是spring-service-http。分别注册的是dubbo端口和http端口。
各位有更好的方案麻烦告知一下。
