### ISSUE TITLE
配置fastjson2序列化不生效，依旧是 hessian

### ISSUE THREAD

**Issue by wjzxc123** [apache/dubbo#13242]
消费者配置
```yaml
server:
  port: 8082
dubbo:
  application:
    name: service-A
    qos-port: 33334
  registry:
    address: multicast://224.5.6.7:1234?unicast=false
  protocol:
    name: dubbo
    port: 38889
    serialization: fastjson2
  consumer:
    check: false
    cache: false
    validation: true
    timeout: 3000
  provider:
    timeout: 3000
```

服务提供者配置
```yaml
server:
  port: 8081
dubbo:
  application:
    name: service-B
    qos-port: 33333
  registry:
    address: multicast://224.5.6.7:1234?unicast=false
  protocol:
    name: dubbo
    port: 38887
    serialization: fastjson2
  consumer:
    check: false
    cache: false
    validation: true
    timeout: 3000
  provider:
    timeout: 3000
```
方法调用时 依旧使用 hessian 方式 
![image](https://github.com/apache/dubbo/assets/32690579/72068141-2d41-43a9-8f45-a810a7b1db34)

dubbo version 3.2.0  spring boot 2.7.2 jdk 17

这里是demo 的地址 https://github.com/wjzxc123/demo
