### ISSUE TITLE
Default config not found for ApplicationConfig

### ISSUE THREAD

**Issue by spq666** [apache/dubbo#13784]
- [ ] I have searched the [issues](https://github.com/apache/dubbo/issues) of this repository and believe that this is not a duplicate.
![image](https://github.com/apache/dubbo/assets/32086265/7483dd28-34da-4192-8287-76d7443166d7)

## Ask your question here
环境：springboot 2.7.5 + nacos 2.2.3 + dubbo 3.2.10

项目启动报错 Default config not found for ApplicationConfig

dubbo配置：

```
dubbo:
  application:
    name: ${spring.application.name}
    qos-port: 33333
    qos-accept-foreign-ip: false
  registry:
    address: 127.0.0.1：8848
    timeout: 20000
    protocol: nacos
    register-mode: interface
    use-as-config-center: false
    use-as-metadata-center: false
    parameters:
      username: ${spring.cloud.nacos.discovery.username}
      password: ${spring.cloud.nacos.discovery.password}
      namespace: ${spring.cloud.nacos.discovery.namespace}
      group: dubbo
      register-consumer-url: true
  protocol:
    port: 20880
    name: dubbo
    serialization: java
```
