### ISSUE TITLE
Multiple registration centers does not take effect

### ISSUE THREAD

**Issue by ai-log** [apache/dubbo#13909]
### Pre-check

- [X] I am sure that all the content I provide is in English.

### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dubbo/issues?q=is%3Aissue) and found no similar feature requirement.

### Apache Dubbo Component

Java SDK (apache/dubbo)

### Descriptions

Dubbo version: 3.1.6
In multi registration centers scenario, when using the same nacos address but different namespaces, only one registration center will take effect.
config such as：
```
dubbo:
  registries:
    reg1:
      address: nacos://127.0.0.1:8848?namespace=namespace1
    reg2:
      address: nacos://127.0.0.1:8848?namespace=namespace2
```

### Are you willing to submit a pull request to fix on your own?

- [ ] Yes I am willing to submit a pull request on my own!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)
