### ISSUE TITLE
[Feature] New Condition route v3.1

### ISSUE THREAD

**Issue by wcy666103** [apache/dubbo#14455]
### Pre-check

- [X] I am sure that all the content I provide is in English.

### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dubbo/issues?q=is%3Aissue) and found no similar feature requirement.

### Apache Dubbo Component

Java SDK (apache/dubbo)

### Descriptions

the updated condition-route like

# dubbo/config/group/{$name}.condition-router

```yaml
configVersion: v3.1
scope: service
key: org.apache.dubbo.samples.CommentService
force: false
runtime: true
enabled: true

#######
conditions:
  - from:
      match: tag=tag1     # disable traffic
  - from:
      match: tag=gray
    to:
      - match: tag!=gray
        weight: 100
      - match: tag=gray
        weight: 900
  - from:
      match: version=v1
    to:
      - match: version=v1
 ```

# dubbo/config/group/{$name}.affinity-router

```yaml
configVersion: v3.1
scope: service # Or application
key: service.apache.com
enabled: true
runtime: true
affinityAware:
  key: region
  ratio: 20
```

### Related issues

https://github.com/apache/dubbo/pull/14356

### Are you willing to submit a pull request to fix on your own?

- [X] Yes I am willing to submit a pull request on my own!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)
