### ISSUE TITLE
[Bug] The interface returns normal data every time, but it always reports a monitoring error.

### ISSUE THREAD

**Issue by gang0713** [apache/dubbo#14959]
### Pre-check

- [X] I am sure that all the content I provide is in English.

### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dubbo/issues?q=is%3Aissue) and found no similar issues.

### Apache Dubbo Component

Java SDK (apache/dubbo)

### Dubbo Version

dubbo:3.3.2
jdk:1.8.0_221
nacos:nacos-server-2.4.3
springboot:2.3.12.RELEASE

### Steps to reproduce this issue

My profile：
nacos:
  host: 127.0.0.1
  port: 8848
  config:
    server-addr: ${nacos.host}:${nacos.port}
  discovery:
    server-addr: ${nacos.host}:${nacos.port}

#dubbo  set
dubbo:
  application:
    id: ${spring.application.name}
    name: ${spring.application.name}
    register-mode: instance
    service-discovery:
      migration: FORCE_APPLICATION
    qos-enable: false
    qos-accept-foreign-ip: false
    serialize-check-status: WARN
  scan:
    base-packages: com.xykq.modules,com.xykq.framework
  registry:
    file: ${user.home}/dubbo-cache/${spring.application.name}/${platform.service.group}/dubbo.cache
    address: nacos://${nacos.host}:${nacos.port}
    group: ${platform.service.group}
  monitor:
    protocol: registry
  protocol:
    name: dubbo
    port: 12308
  #  server: netty4
  #    serialization: kryo
  provider:
    retries: 0
    delay: -1
    timeout: 30000
  consumer:
    timeout: 30000
    check: false  # 服务启动时检查被调用服务是否可用
    client: netty4
    retries: 0    # 服务调用重试次数

### What you expected to happen

2024-12-02 18:29:13.134  WARN 51918 --- [2308-thread-102] o.a.d.m.s.MonitorFilter                  :  [DUBBO] Failed to monitor count service dubbo://172.17.89.123:12308/com.xykq.modules.business.services.IBusinessManageService?anyhost=true&application=spring-boot-provider-scm&background=false&bind.ip=172.17.89.123&bind.port=12308&delay=-1&deprecated=false&dubbo=2.0.2&dynamic=true&executor-management-mode=isolation&file-cache=true&generic=false&group=pro&interface=com.kq.modules.business.services.IBusinessManageService&methods=countBusinessOrder,countFactorOrder,countFactorOrderReceive,countPlatServiceFee,downloadContractBySignFlowsInfo,executeAgainSignFlow,executeEnterpriseAuditOrder,executeFactorBuyOrder,executeFactorOrderStatus,executeFactorSignFlows,executeFundCancleOrder,executeFundCofirmOrderToCore,executeFundConfirmOrder,executeFundOrderBadDebt,executePutFundOrder,executeSupplyCancelConfirm,findBusinessOrderByFundAccount,findBusinessOrderTotal,findCoreEnterpriseAll,findEnterpriseFundOrderList,findExtFileByCondition,findExtFileById,findExtFileOrderList,findFactorFundOrderList,findFactorListByOrderId,findFactorOrderByConditon,findFundAccountOrderByFundAccountId,findFundInfoByOrderId,findFundOrderAllList,findFundOrderDetail,findFundOrderDetailByCore,findFundOrderDetailByFactor,findFundOrderDetailById,findFundOrderList,findIsExistOrderByFundAccountId,findOrderInfoById,findOverdueFundOrderDetail,findOverdueFundOrderList,findOverdueFundOrderListTotal,findTBusinessOperateRecordList,findTBusinessOrder,findTBusinessOrderExpand,findTCoreEnterpriseOrderList,findTFactorOrderById,findTodoCount,fundListByIds,fundOrderWaitBuyList,insertExtFileOrder,insertExtFileRemark,insertFactorOrderByRegister,insertFundOrder,insertFundOrderAll&pid=51918&prefer.serialization=hessian2,fastjson2&qos.accept.foreign.ip=false&qos.enable=false&register-mode=instance&release=3.3.2&retries=0&revision=1.0.0&serialize.check.status=WARN&service-name-mapping=true&side=provider&timeout=30000&timestamp=1733132619161&version=1.0.0, cause: null, dubbo version: 3.3.2, current host: 172.17.89.123, error code: 0-14. This may be caused by , go to https://dubbo.apache.org/faq/0/14 to find instructions. 

java.lang.NullPointerException: null
	at org.apache.dubbo.monitor.support.MonitorFilter.collect(MonitorFilter.java:170) ~[dubbo-3.3.2.jar!/:3.3.2]
	at org.apache.dubbo.monitor.support.MonitorFilter.onResponse(MonitorFilter.java:129) ~[dubbo-3.3.2.jar!/:3.3.2]
	at org.apache.dubbo.rpc.cluster.filter.FilterChainBuilder$CallbackRegistrationInvoker.lambda$invoke$1(FilterChainBuilder.java:221) ~[dubbo-3.3.2.jar!/:3.3.2]
	at org.apache.dubbo.rpc.AsyncRpcResult.lambda$whenCompleteWithContext$0(AsyncRpcResult.java:254) ~[dubbo-3.3.2.jar!/:3.3.2]
	at java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:760) [?:1.8.0_221]
	at java.util.concurrent.CompletableFuture.uniWhenCompleteStage(CompletableFuture.java:778) [?:1.8.0_221]
	at java.util.concurrent.CompletableFuture.whenComplete(CompletableFuture.java:2140) [?:1.8.0_221]
	at org.apache.dubbo.rpc.AsyncRpcResult.whenCompleteWithContext(AsyncRpcResult.java:250) [dubbo-3.3.2.jar!/:3.3.2]
	at org.apache.dubbo.rpc.cluster.filter.FilterChainBuilder$CallbackRegistrationInvoker.invoke(FilterChainBuilder.java:198) [dubbo-3.3.2.jar!/:3.3.2]
	at org.apache.dubbo.rpc.protocol.dubbo.DubboProtocol$1.reply(DubboProtocol.java:167) [dubbo-3.3.2.jar!/:3.3.2]
	at org.apache.dubbo.remoting.exchange.support.header.HeaderExchangeHandler.handleRequest(HeaderExchangeHandler.java:110) [dubbo-3.3.2.jar!/:3.3.2]
	at org.apache.dubbo.remoting.exchange.support.header.HeaderExchangeHandler.received(HeaderExchangeHandler.java:205) [dubbo-3.3.2.jar!/:3.3.2]
	at org.apache.dubbo.remoting.transport.DecodeHandler.received(DecodeHandler.java:52) [dubbo-3.3.2.jar!/:3.3.2]
	at org.apache.dubbo.remoting.transport.dispatcher.ChannelEventRunnable.run(ChannelEventRunnable.java:64) [dubbo-3.3.2.jar!/:3.3.2]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_221]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_221]
	at org.apache.dubbo.common.threadlocal.InternalRunnable.run(InternalRunnable.java:39) [dubbo-3.3.2.jar!/:3.3.2]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_221]

### Anything else

no

### Are you willing to submit a pull request to fix on your own?

- [X] Yes I am willing to submit a pull request on my own!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by aofall** [comment]
I tried to restore the profile yaml configuration as you provided follows:

```
nacos:
  host: 127.0.0.1
  port: 8848
  config:
    server-addr: ${nacos.host}:${nacos.port}
  discovery:
    server-addr: ${nacos.host}:${nacos.port}
#dubbo set
dubbo:
  application:
    id: ${spring.application.name}
    name: ${spring.application.name}
  register-mode: instance
  service-discovery:
    migration: FORCE_APPLICATION
    qos-enable: false
    qos-accept-foreign-ip: false
    serialize-check-status: WARN
  scan:
    base-packages: com.xykq.modules,com.xykq.framework
  registry:
    file: ${user.home}/dubbo-cache/${spring.application.name}/${platform.service.group}/dubbo.cache
    address: nacos://${nacos.host}:${nacos.port}
    group: ${platform.service.group}
  monitor:
    protocol: registry
  protocol:
    name: dubbo
    port: 12308
```

The dubbo-monitor is mark as deprecated, you can remove this config if you didn't need it. 

```
dubbo:
  monitor:
    protocol: registry
```

Or you can use the new dubbo-metrics instead it
