### ISSUE TITLE
[Bug] how to config max request header size in dubbo rest?

### ISSUE THREAD

**Issue by multiplyzero** [apache/dubbo#14988]
### Pre-check

- [X] I am sure that all the content I provide is in English.

### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dubbo/issues?q=is%3Aissue) and found no similar issues.

### Apache Dubbo Component

Java SDK (apache/dubbo)

### Dubbo Version

2.6.7

### Steps to reproduce this issue

dubbo 2.6.7
when i use dubbo rest and request cookie is large，the server back httpcode 413， so how can i set maxRequestHeaderSize in dubbo rest???

### What you expected to happen

dubbo 2.6.7
when i use dubbo rest and request cookie is large，the server back httpcode 413， so how can i set maxRequestHeaderSize in dubbo rest???

### Are you willing to submit a pull request to fix on your own?

- [X] Yes I am willing to submit a pull request on my own!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by aofall** [comment]
Upgrade dubbo version to 3.2 first, then try to add the following configuration and set it by yourself.

```
dubbo:
  application:
    parameters:
      # set header size, the default is 8192
      max.header.size: 8192
      # set the netty chunk size, the default is 8192
      max.chunk.size: 8192
      # set request object size, the default is 1024 * 1024 * 10 = 10,485,760
      max.request.size: 10485760
```
