### ISSUE TITLE
[Bug] dubbo config `dubbo.registry.parameters.namespace` is invalid

### ISSUE THREAD

**Issue by wzkris** [apache/dubbo#15114]
### Pre-check

- [x] I am sure that all the content I provide is in English.

### Search before asking

- [x] I had searched in the [issues](https://github.com/apache/dubbo/issues?q=is%3Aissue) and found no similar issues.

### Apache Dubbo Component

Java SDK (apache/dubbo)

### Dubbo Version

dubbo-spring-boot-starter V3.3.3

### dubbo config.
```
dubbo:
  protocol:
    name: dubbo
    port: -1
  application:
    logger: slf4j
    metadataType: remote
    register-mode: instance
    service-discovery:
      migration: FORCE_APPLICATION
  registry:
    address: nacos://${spring.cloud.nacos.server-addr}
    register-mode: instance
    group: DUBBO_GROUP
    username: ${spring.cloud.nacos.username}
    password: ${spring.cloud.nacos.password}
    parameters:
      namespace: dubbo-dev
  consumer:
    cache: false
    validation: jvalidationNew
    retries: 0
    check: false
```
It will register application-dev namespace which is my application namespace.

![Image](https://github.com/user-attachments/assets/2e1e92e6-2e79-4222-8ecc-c08e90ce29bd)

Strangely, with the same configuration, I can register to the correct namespace in another program.

![Image](https://github.com/user-attachments/assets/438b6a5d-2b99-4124-b7a0-b006586ae642)

### Steps to reproduce this issue

Create a springboot project using mine config

### What you expected to happen

look second picture

### Are you willing to submit a pull request to fix on your own?

- [ ] Yes I am willing to submit a pull request on my own!

### Code of Conduct

- [x] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)
