### ISSUE TITLE
[Feature] How do I enable the virtual thread function in 3.3?

### ISSUE THREAD

**Issue by JavaLionLi** [apache/dubbo#15156]
### Pre-check

- [x] I am sure that all the content I provide is in English.

### Search before asking

- [x] I had searched in the [issues](https://github.com/apache/dubbo/issues?q=is%3Aissue) and found no similar feature requirement.

### Apache Dubbo Component

Java SDK (apache/dubbo)

### Descriptions

How do I enable the virtual thread function in 3.3?
Or you can have a document address
I didn't find it in the documentation

### Are you willing to submit a pull request to fix on your own?

- [x] Yes I am willing to submit a pull request on my own!

### Code of Conduct

- [x] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by songxiaosheng** [comment]
In Java 19 and 20, try  Executors.newVirtualThreadPerTaskExecutor

```java
@Configuration
public class DubboConfig {
    @Bean
    public ExecutorService virtualThreadExecutor() {
        return Executors.newVirtualThreadPerTaskExecutor();
    }
}

```

```yaml
dubbo:
  protocol:
    name: dubbo
    port: 20880
    dispatcher: all
    threadpool: cached
    # 关键配置：使用虚拟线程
    executor: virtualThreadExecutor
```

**Comment by JavaLionLi** [comment]
> In Java 19 and 20, try Executors.newVirtualThreadPerTaskExecutor
> 
> @Configuration
> public class DubboConfig {
>     @Bean
>     public ExecutorService virtualThreadExecutor() {
>         return Executors.newVirtualThreadPerTaskExecutor();
>     }
> }
> dubbo:
>   protocol:
>     name: dubbo
>     port: 20880
>     dispatcher: all
>     threadpool: cached
>     # 关键配置：使用虚拟线程
>     executor: virtualThreadExecutor

是否可以兼容springboot的yml虚拟线程开关呢 在dubbo-spring-boot-starter里 这样是可以兼容jdk17和jdk21的只需要一个开关

**Comment by JavaLionLi** [comment]
https://github.com/apache/dubbo/issues/15158

**Comment by JavaLionLi** [comment]
```
dubbo:
  protocol:
    name: dubbo
    port: 20880
    threadpool: virtual
```
上面说的配置不对 直接配线程池类型为虚拟线程即可
