### ISSUE TITLE
Need to publish artifacts to snapshot repository if CI passes

### ISSUE THREAD

**Issue by beiwei30** [apache/dubbo#2335]
I'm not quite sure if it's done, but what I suggest is, if it's not done yet, we should consider to add instruction in .travis.yaml to publish all artifacts to snapshot repository every time when CI passes, to make everyone's life easier.

**Comment by htynkn** [comment]
any update for this?

**Comment by chickenlj** [comment]
https://docs.travis-ci.com/user/encryption-keys/
https://jeanchristophegay.com/deploy-snapshot-travis-ci-en/
https://github.com/stefanbirkner/travis-deploy-to-maven-central

**Comment by chickenlj** [comment]
One demo project for the same purpose.

https://github.com/stefanbirkner/travis-deploy-to-maven-central

**Comment by chickenlj** [comment]
Maybe `deploy` can do the same thing as `after_success`:
```yaml
deploy:
  provider: script
  script: "cp .travis.settings.xml $HOME/.m2/settings.xml && mvn deploy"
  skip_cleanup: true
  on:
    tags: true
```
