### ISSUE TITLE
使用 eager 线程池类型，缺少keepAliveTime参数配置入口

### ISSUE THREAD

**Issue by foreveryang321** [apache/dubbo#3687]
### Environment

* Dubbo version: 2.6.6、2.7.0
* Operating System version: 
* Java version: 

### Steps to reproduce this issue

```java
public class EagerThreadPool implements ThreadPool {

    @Override
    public Executor getExecutor(URL url) {
        String name = url.getParameter(Constants.THREAD_NAME_KEY, Constants.DEFAULT_THREAD_NAME);
        int cores = url.getParameter(Constants.CORE_THREADS_KEY, Constants.DEFAULT_CORE_THREADS);
        int threads = url.getParameter(Constants.THREADS_KEY, Integer.MAX_VALUE);
        int queues = url.getParameter(Constants.QUEUES_KEY, Constants.DEFAULT_QUEUES);
        int alive = url.getParameter(Constants.ALIVE_KEY, Constants.DEFAULT_ALIVE);
        ....
```
```yaml
dubbo:
  application:
    name: user-service
    qos-enable: false
  protocol:
    name: dubbo
    port: -1
    threadpool: eager
    threads: 128
    alive: 30000
  registry:
    address: multicast://224.5.6.7:1234
  provider:
    delay: -1
    timeout: 20000
    retries: 0
#    threadpool: eager
#    threads: 128
#    alive: 30000
```

### Expected Result

希望使用eager线程池类型的时候，可以提供alive的配置入口
