### ISSUE TITLE
metadata report doesn't support the placeholder

### ISSUE THREAD

**Issue by iapplejohn** [apache/dubbo#3884]
In the application.yml, the address contains place holder, couldn't be replaced at runtime.
Instead, the address of metadata-report would be zookeeper://

```
dubbo:
  application:
    name: test
  registry:
    protocol: zookeeper
    address: ${middleware.zk.address}
    simplified: true
  metadata-report:
    address: zookeeper://${middleware.zk.address}
    valid: true
  config:
    multiple: false
```
