### ISSUE TITLE
dubbo2.7.2, nacos1.0修改配置不生效

### ISSUE THREAD

**Issue by greatle** [apache/dubbo#4262]
Dubbo version: 2.7.2
Operating System version: window10
Java version: 1.8.151

问题步骤：

1. 部署nacos1.0版本
2. 启动一个dubbo服务端
3. 启动一个dubbo消费端
dubbo消费端主要配置为：

```xml
    <dubbo:application name="remote-client-app"  />
    <dubbo:registry address="nacos://192.168.1.16:8848" />
    <dubbo:metadata-report address="nacos://192.168.1.16:8848" />
    <dubbo:config-center address="nacos://192.168.1.16:8848" />
    <context:component-scan base-package="com.test.remote.client"/>
    <dubbo:reference id="remoteService" interface="com.test.remote.intf.RemoteCallService" check="true"  timeout="30000" mock="true"/>
```

4. 测试消费端调用，能够正常调用，并返回服务端提供的值。
5. 在nacos控制台中修改消费端的配置项：dataid为：`remote-client-app.configurators`，group为：`dubbo`，具体内容修改为模拟服务降级处理，修改内容如下：

```yml
    scope: application
    key: remote-client-app
    enabled: true
    configs:
    - side: consumer
      parameters:
        mock: force:return+'this is test null value'
```

修改后发布
6. 此时消费端期望返回'this is test null value'，但实际上仍然返回服务端的正确值。如果重启服务端，则此时消费端才返回期望的'this is test null value'值。

**Comment by beiwei30** [comment]
pls. try `2.7.3` or above, which is `2.7.4-SNAPSHOT` with https://github.com/apache/dubbo-samples/tree/master/dubbo-samples-nacos/dubbo-samples-nacos-override. I verified it should work. I use the following rule:

```yaml
---
configVersion: v2.7
scope: application
key: governance-serviceoverride-consumer
enabled: true
configs:
- addresses: [0.0.0.0]
  side: consumer
  parameters:
    timeout: 6000
    mock: force:return+'this is mock'
...

```
