### ISSUE TITLE
k8s滚动升级场景时下线Dubbo应用容器节点前没法通过Dubbo自动切断进入该节点的入口Dubbo请求流量

### ISSUE THREAD

**Issue by chenkline** [apache/dubbo#4361]
### Environment

* Dubbo version: 2.7.2
* Operating System version: centos 7.3
* Java version: 8u144

### 问题描述

k8s环境下，dubbo应用间调用时容器与容器之间直接调用，但是k8s滚动升级时下线一个容器节点前，没法自动通过dubbo进行流量切换，没法自动切断进入该应用容器节点的入口请求流量

**Comment by chickenlj** [comment]
我想我们需要调研一下K8S的标准停机回调入口，Dubbo提供必要的支持

**Comment by cvictory** [comment]
> ### Environment
> * Dubbo version: 2.7.2
> * Operating System version: centos 7.3
> * Java version: 8u144
> 
> ### 问题描述
> k8s环境下，dubbo应用间调用时容器与容器之间直接调用，但是k8s滚动升级时下线一个容器节点前，没法自动通过dubbo进行流量切换，没法自动切断进入该应用容器节点的入口请求流量

直接调用的情形下，不走服务发现？ 直接调用，需要是集群吗？

**Comment by cvictory** [comment]
配置中增加：
```
spec:
  contaienrs:
  - name: my-awesome-container
    lifecycle:
      preStop:
        exec:
          command: ["/bin/sh"，"-c"，"/pre-stop.sh"]
```

通过调用： http://127.0.0.1:22222/offline   方式可以优雅下线。 所以在pre-stop.sh中可以调用： 

`curl http://ip:22222/offline`

参考：https://juejin.im/post/5ca2caf6e51d450b007a6f72
https://kubernetes.io/docs/concepts/containers/container-lifecycle-hooks/
