### ISSUE TITLE
tag rule should support anyhost

### ISSUE THREAD

**Issue by beiwei30** [apache/dubbo#4393]
The following rule doesn't work. We should support **0.0.0.0**.

```yaml
---
force: false
runtime: true
enabled: true
priority: 1
key: governance-tagrouter-provider
tags:
- name: tag1
  addresses: ["0.0.0.0:20881"]
- name: tag2
  addresses: ["0.0.0.0:20880"]
...
```
