### ISSUE TITLE
There is no metadata available, please update to Dubbo2.7, or check your config center configuration in application.properties

### ISSUE THREAD

**Issue by seedscoder** [apache/dubbo#5831]
### Environment

* Dubbo version: 2.7.5
* Spring Boot version: 2.2.2.RELEASE
* Dubbo Admin version : dubbo-admin-0.2.0
* Operating System version: windows 10
* Java version: jdk1.8.0_212

### Steps to reproduce this issue

1. Service Provider config :
```yml
spring:
  application:
    name: dubbo-provider
dubbo:
  protocol:
    port: -1
    name: dubbo
#  registry:
#    address: zookeeper://127.0.0.1:2181
#    simplified: true
#  metadata-report:
#    address: zookeeper://127.0.0.1:2181
  config-center:
    address: zookeeper://127.0.0.1:2181
  scan:
    base-packages: dubbo.provider.service.impl
```
2. Zookeeper config :
![zookeeper配置](https://user-images.githubusercontent.com/34568397/75989143-b438a680-5f2d-11ea-9338-6928c51ce0f3.png)

3. Serivce Consumer config :
```yml
spring:
  application:
    name: dubbo-consumer

dubbo:
  config-center:
    address: zookeeper://127.0.0.1:2181
  protocol:
    port: -1
    name: dubbo
  consumer:
    check: false
    timeout: 15000
```
Pls. provide [`https://github.com/seedscoder/dubbo-demo.git`] to reproduce this issue.

### Expected Result

**I want to use the metadata capabilities provided by dubbo 2.7.5**

### Actual Result
![结果](https://user-images.githubusercontent.com/34568397/75989249-e34f1800-5f2d-11ea-888a-02386050b977.png)
