### ISSUE TITLE
ZoneAware doesn't work with zone configuration

### ISSUE THREAD

**Issue by AlbumenJ** [apache/dubbo#6022]
### Environment

* Dubbo version: 2.7.7-SNAPSHOT (apache/dubbo@0def3dc3)
* Operating System version: Windows 10
* Java version: JDK 1.8

### Steps to reproduce this issue

1. create a provider named `dubbo-1` , register to registry-1 (nacos://127.0.0.1:8848) and tag it with `dubbo.registry.zone = rega`
2. create a provider named `dubbo-2` , register to registry-2 (nacos://127.0.0.1:8849) and tag it with `dubbo.registry.zone = regb`
3. create a consumer named `dubbo-3` , register to registry-1 and registry-2 and tag them with zone properties
4. consumer unable to comsume the specific zone when assign `RpcContext.getContext().setAttachment("registry_zone","regb");`

### Main Properties of the demo

```
dubbo:
  scan:
    base-packages: cn.albumenj
  protocol:
    name: dubbo
    port: -1
  registry:
    address: nacos://127.0.0.1:8848
    zone: rega
  application:
    name: dubbo-1
```

```
dubbo:
  scan:
    base-packages: cn.albumenj
  protocol:
    name: dubbo
    port: -1
  registry:
    address: nacos://127.0.0.1:8849
    id: regb
    zone: regb
    use-as-config-center: false
  application:
    name: dubbo-2
```

```
dubbo:
  scan:
    base-packages: cn.albumenj
  protocol:
    name: dubbo
    port: -1
  application:
    name: dubbo-3
  registries:
    rega:
      id: rega
      address: nacos://127.0.0.1:8848
      zone: rega
    regb:
      id: regb
      address: nacos://127.0.0.1:8849
      zone: regb
```

```
@Component
public class Runner implements CommandLineRunner {
    @Reference
    private DemoService demoService;

    @Override
    public void run(String... args) throws Exception {
        for (int i = 0; i < 10; i++) {
            RpcContext.getContext().setAttachment("registry_zone","regb");
            System.out.println(demoService.sayHello("Dubbo-3"));
        }
    }
}
```

### Actual Result

In `ZoneAwareClusterInvoker`, the related source code is below
```
    public Result doInvoke(Invocation invocation, final List<Invoker<T>> invokers, LoadBalance loadbalance) throws RpcException {

    ···

        // providers in the registry with the same zone
        String zone = (String) invocation.getAttachment(REGISTRY_ZONE);
        if (StringUtils.isNotEmpty(zone)) {
            for (Invoker<T> invoker : invokers) {
                MockClusterInvoker<T> mockClusterInvoker = (MockClusterInvoker<T>) invoker;
                if (mockClusterInvoker.isAvailable() && zone.equals(mockClusterInvoker.getRegistryUrl().getParameter(REGISTRY_KEY + "." + ZONE_KEY))) {
                    return mockClusterInvoker.invoke(invocation);
                }
            }
            String force = (String) invocation.getAttachment(REGISTRY_ZONE_FORCE);
            if (StringUtils.isNotEmpty(force) && "true".equalsIgnoreCase(force)) {
                throw new IllegalStateException("No registry instance in zone or no available providers in the registry, zone: "
                        + zone
                        + ", registries: " + invokers.stream().map(invoker -> ((MockClusterInvoker<T>) invoker).getRegistryUrl().toString()).collect(Collectors.joining(",")));
            }
        }

    ···

    }

```

When I trace it, the `zone` get from attachment is correct, but `getRegistryUrl().getParameter(REGISTRY_KEY + "." + ZONE_KEY)` unable get the correct zone of registry.

The registry url is like this

```
nacos://127.0.0.1:8848/org.apache.dubbo.registry.RegistryService?application=dubbo-3&dubbo=2.0.2&pid=193320&qos.enable=false&release=2.7.7-SNAPSHOT&timestamp=1586922659951&zone=rega
```

In the url, the key of zone is `zone` but `getParameter(REGISTRY_KEY + "." + ZONE_KEY)` use `registry.zone`.
