### ISSUE TITLE
Dubbo 多注册中心中Zone问题 

### ISSUE THREAD

**Issue by kaiguoyuanshuai** [apache/dubbo#6529]
- [ ] I have searched the [issues](https://github.com/apache/dubbo/issues) of this repository and believe that this is not a duplicate.
- [ ] I have checked the [FAQ](https://github.com/apache/dubbo/blob/master/FAQ.md) of this repository and believe that this is not a duplicate.

### Environment

* Dubbo version: 2.7.8
* Operating System version: mac 
* Java version: 1.8

### Steps to reproduce this issue
使用Dubbo的多注册中心和Zone 功能，一直在两个注册中心中负载，设置zone 不生效 ，设置 preferred: true 不生效
consumer
```yml
dubbo:
  consumer:
    check: false
  registries:
    test:
      id: test
      protocol: zookeeper
      address: zookeeper://localhost:2181?zone=test
      use-as-config-center: false
      preferred: true
      registry.zone: test
    dev:
      id: dev
      protocol: zookeeper
      address: dev-zk1.zk.com:2181
      use-as-config-center: false
      registry.zone: dev
  config:
    multiple: true

```
provider1
```yml
dubbo:
  protocol:
    port: 12322
    name: dubbo
  config:
    multiple: true
  registry:
    id: dev
    zone: dev
    use-as-config-center: false
    address: zookeeper://dev-zk1.zk.com:2181
  config-center:
    address: zookeeper://dev-zk1.zk.com:2181
  metadata-report:
    address:  zookeeper://dev-zk1.zk.com:2181
```
provider1
```yml
dubbo:
  protocol:
    port: 12311
    name: dubbo
  config:
    multiple: true
  registry:
    id: test
    zone: test
    use-as-config-center: false
    address: zookeeper://localhost:2181
  config-center:
    address: zookeeper://localhost:2181
  metadata-report:
    address: zookeeper://localhost:2181

```

### Expected Result
应该优先调用    preferred: true 的注册中心

### Actual Result
两个注册中心的服务随机调用
