### ISSUE TITLE
dubbo2.7.6+nacos1.2.1(springcloud方式) 配置延迟暴露无效

### ISSUE THREAD

**Issue by nickszeng** [apache/dubbo#6765]
### Environment

* Dubbo version: 2.7.6
* Operating System version: win10x64
* Java version: 1.8

### Steps to reproduce this issue

1. pom依赖
```java 
<dependency>
    <groupId>com.alibaba.cloud</groupId>
    <artifactId>spring-cloud-starter-dubbo</artifactId>
</dependency>
<dependency>
    <groupId>com.alibaba.cloud</groupId>
    <artifactId>spring-cloud-starter-alibaba-nacos-discovery</artifactId>
</dependency>
```

2. 配置信息
```yml
spring:
  cloud:
    nacos:
      discovery:
        server-addr: '127.0.0.1:8848'
        namespace: ${xxx}
dubbo:
   application:
     id: samples-dubbo-provider
    name: samples-dubbo-provider
  registry:
      address: 'spring-cloud://locahost' ##配置spring-cloud注册协议
  protocol:
    name: dubbo
    port: -1
  provider:
      ##配置延迟暴露1s
      delay: 1000
```
Pls. provide [GitHub address] to reproduce this issue.

### Expected Result

What do you expected from the above steps？
注册信息缺失：
![1600397688(1)](https://user-images.githubusercontent.com/12146245/93550371-d5c72000-f99d-11ea-8914-b089d80d4760.jpg)

调用出错：
No provider available for the service

### Actual Result

去掉 delay配置 调用正常 

```
Just put your stack trace here!
```
