### ISSUE TITLE
本地dubbo配置订阅后，启动失败

### ISSUE THREAD

**Issue by zhouyk-library** [apache/dubbo#6901]
### 环境

Dubbo Spring Boot (v2.7.8) : https://github.com/apache/dubbo-spring-boot-project
Dubbo (v2.7.8) : https://github.com/apache/dubbo
spring-cloud-alibaba.version  2.2.3.RELEASE
spring-cloud.version Hoxton.SR5
nacos 1.3.1

### application.yml
```
dubbo:
  scan:
    base-packages: com.xxx.xxxx
  protocol:
    name: dubbo
    port: 28004
  consumer:
    check: false
    timeout: 6000
  registry:
    address: spring-cloud://localhost
  cloud:
    subscribed-services: greey-good-demo2-server(端口号为28005)
```
### 问题：启动时报异常，但是nacos注册是没有问题的

org.apache.dubbo.remoting.RemotingException: client(url: dubbo://192.168.1.157:28005/com.alibaba.cloud.dubbo.service.DubboMetadataService?anyhost=true&application=greey-good-demo1-server&bind.ip=192.168.1.157&bind.port=28005&check=false&codec=dubbo&deprecated=false&dubbo=2.0.2&dynamic=true&generic=true&group=greey-good-demo2-server&heartbeat=60000&interface=com.alibaba.cloud.dubbo.service.DubboMetadataService&methods=getAllServiceKeys,getServiceRestMetadata,getExportedURLs,getAllExportedURLs&pid=17868&qos.enable=false&register.ip=10.200.240.16&release=2.7.8&remote.application=greey-good-demo2-server&revision=2.2.3.RELEASE&side=consumer&sticky=false&timeout=6000&timestamp=1605234261450&version=1.0.0) failed to connect to server /192.168.1.157:28005 client-side timeout 3000ms (elapsed: 3732ms) from netty client XXX.XXX.XXX.XXX using dubbo version 2.7.8

XXX.XXX.XXX.XXX 是vpn的IP,部分机器无此问题

取掉 subscribed-services: greey-good-demo2-server(端口号为28005) 则不会发生问题
