### ISSUE TITLE
请问dubbo2.7怎样通过配置中心获得一组属性配置？类似于springboot的@@ConfigurationProperties("XXX")形式来获取yaml的值

### ISSUE THREAD

**Issue by develpoerX** [apache/dubbo#6994]
```
test:
    key1: |
      kind:
        - kind1:
            name: "fruit"
    key2: |
      kind:
        - kind2:
            name2: "fruit2"
```
上面是我想要配置的属性格式，但是我发现properties配置文件里面都是key:value的形式。我想通过：get属性（test）,或者key1和key2的属性值为map形式（eg,key1:kind:- kind1:name: "fruit"）,因为我后面想进一步把value的值近一步转换为map。
2.dubbo中有可以直接使用yaml配置文件的案例吗？如果可以直接读取yaml，上面的问题也就解决了，只是我看文档没有发现可以这么操作的。希望能得到指教一下。十分感谢。
