### ISSUE TITLE
当使用nacos作为配置中心时配置列表和服务列表出现了很多无用的配置

### ISSUE THREAD

**Issue by ZhangShaoWu** [apache/dubbo#7075]
![image](https://user-images.githubusercontent.com/19930444/103538052-78b19480-4ed0-11eb-82ab-8b33514e4c82.png)
![image](https://user-images.githubusercontent.com/19930444/103538083-88c97400-4ed0-11eb-90ab-57dcf0330a01.png)

**Comment by KeRan213539** [comment]
图1中的是dubbo 配制中心和元数据中心的数据, 如果不希望写到nacos中,可以通过如下配制(dubbo spring boot)指定到zookeeper:
```
dubbo:
  metadata-report:
    address: nacos://127.0.0.1:8848
    group: DEFAULT_GROUP
  config-center:
    address: nacos://127.0.0.1:8848
    group: DEFAULT_GROUP
```
图2中是dubbo 接口级的注册信息.
