### ISSUE TITLE
dubbo在什么时候清理RpcContext和FutureContext

### ISSUE THREAD

**Issue by dev-lluo** [apache/dubbo#7271]
最近在项目中使用到dubbo;出现了由于RpcContext和FutureContext一直持有参数和返回值导致的内存泄漏问题
![image](https://user-images.githubusercontent.com/15041874/109134749-5716b000-7791-11eb-9f3e-45d9b03654ba.png)
![image](https://user-images.githubusercontent.com/15041874/109135182-c12f5500-7791-11eb-98d0-63723c082009.png)
### dubbo版本
```
<!-- Apache Dubbo -->
<dependency>
<groupId>org.apache.dubbo</groupId>
<artifactId>dubbo-dependencies-bom</artifactId>
<version>2.7.8</version>
<type>pom</type>
<scope>import</scope>
</dependency>
```

### consumer配置

```
dubbo:
  application:
    name: xxx-server
  protocol:
    name: hessian
    payload: 16777216
 consumer:
    timeout: 30000
  service:
    url: hessian://xxx:12345
    version: 1.0.0
```
### provider配置

```
application:
  name: xxx-server
  protocol:
   name: hessian
   port: 12345
   payload: 16777216
  registry:
    address: N/A
  scan:
    base-packages: xxx.service.impl
  provider:
    serialization: infodator
    timeout: 30000
```

### 调用逻辑

provider中提供一个method1和method2方法;consumer中在一个业务中需要调用method1和method2两个方法以组合结果集输出(大致为输入一个excel解析出的列表给provider然后返回一个经过处理的集合;故数据比较大)

in==>consumer.service==>[provider.method1,provider.method2]==>combine==>out

原来method1和method2是串行调用,后由于数据量上升;method1和method2在处理时比较耗时;且两个方法没有依赖关系;在consumer端改为使用CompletableFuture并行调用以缩短接口响应时间,此时出现内存泄漏(如上图所示).

```
 CompletableFuture.supplyAsync(() -> {
   Object resultPart1 = provider.method1(x1,x2);
  return resultPart1;
}, executor).thenCombineAsync(CompletableFuture.supplyAsync(() -> {
  Object resultPart2 =  provider.method2(x1,x2);
  return resultPart2;
}, executor), combiner, executor).get(3, TimeUnit.SECONDS);
```

其中executor为上图中指出的自定义线程池(最小存活数为30),参数x1和返回值的大小在几MB到几百MB,故context不被清理时内存将很快被耗尽.

目前暂时通过自定义一个过滤器在invoke之后清理context以移除相关引用
```
@Override
public Result invoke(Invoker<?> invoker, Invocation invocation) throws RpcException {
  try {
   return invoker.invoke(invocation);
  } finally {
   RpcContext.removeContext();
   FutureContext.getContext().setFuture(null);
   log.info("clear-rpc-context {}", RpcContext.getContext().getArguments());
  }
}
```

### 如果dubbo不会自动清理RpcContext和FutureContext;那我目前的处理方式会不会带来bug?

烦请予以解答
