### ISSUE TITLE
指定版本号问题

### ISSUE THREAD

**Issue by HuShao96** [apache/dubbo#7847]
项目a是消费者。指定消费提供者version：1.0.0；@DubboReference(version = "1.0.0")
项目b是提供者，分别启动两个服务
version：1.0.0:

```
server:
  port: 6201
dubbo:
  protocols:
    dubbo:
      name: dubbo
      port: -1
  provider:
    version: '1.0.0'
spring:
  application:
    name: flow-process-center
version:2.0.0:
```

```
server:
  port: 6202
dubbo:
  protocols:
    dubbo:
      name: dubbo
      port: -1
  provider:
    version: '2.0.0'
spring:
  application:
    name: flow-process-center
```
；
但是项目a还是会轮训调用项目b的两个不同版本的服务；
spring cloud alibaba 2021.1+dubbo;
![image](https://user-images.githubusercontent.com/26806329/119289260-d7f42380-bc7c-11eb-9d65-9bdd58ea3bea.png)
