### ISSUE TITLE
dubbo 3.0.0 +  spring boot + nacos always add one config on bootstrap

### ISSUE THREAD

**Issue by EarthChen** [apache/dubbo#8096]
### Environment

* Dubbo version: 3.0.0
* Operating System version: macos
* Java version: 8
* spring boot: 2.3.9.RELEASE
* dubbo-spring-boot-starter:3.0.0
* dubbo-registry-nacos:3.0.0

#### build.gradle
```gradle
compile('com.alibaba.nacos:nacos-client:2.0.2')
implementation("org.apache.dubbo:dubbo-spring-boot-starter:3.0.0")
implementation("org.apache.dubbo:dubbo-registry-nacos:3.0.0")
```

#### application.yaml
```yaml
dubbo:
  scan:
    base-packages: com.test.dubbo.impl
  registry:
    address: nacos://127.0.0.1:8848?username=nacos&password=nacos&namespace=test
    username: nacos
    password: nacos
    group: test
    parameters:
      group: test
      namespace: test
      username: nacos
      password: nacos
  protocol:
    port: 20880
```

![image](https://user-images.githubusercontent.com/20179425/122548623-2de19e80-d064-11eb-94b6-0c0db5eae1a9.png)

Always add one when you reboot..

but dubbo:2.7.12 will not happen and config list less
