### ISSUE TITLE
请问使用dubbo admin 0.3版本如何手动下线服务提供者啊？

### ISSUE THREAD

**Issue by startjava** [apache/dubbo#8505]
```
# 配置dubbo
dubbo:
  registry:
    # 注册中心地址
    address: zookeeper://127.0.0.1
    port: 2181
    dynamic: false
```

上面是服务提供者的yaml文件，配置了dynamic为false，

但进入dubbo admin界面没有找到服务下线的菜单啊
