### ISSUE TITLE
triple不支持应用级地址发现

### ISSUE THREAD

**Issue by feng996** [apache/dubbo#8599]
- [ ] I have searched the [issues](https://github.com/apache/dubbo/issues) of this repository and believe that this is not a duplicate.
- [ ] I have checked the [FAQ](https://github.com/apache/dubbo/blob/master/FAQ.md) of this repository and believe that this is not a duplicate.

### Environment

* Dubbo version: 3.x
* Operating System version: Ubuntu 18.04.5
* Java version: 11
* nacos version: 1.4.2

### Steps to reproduce this issue

1. provider配置
```
dubbo:
  application:
    metadata-type: remote
    register-mode: instance
  registry:
    address: nacos://${nacos.host}:${nacos.port}
  protocol:
    name: tri
    serialization: protobuf
```
2. consumer配置
```
dubbo:
  application:
    metadata-type: remote
    service-discovery:
      migration: APPLICATION_FIRST
  registry:
    address: nacos://${nacos.host}:${nacos.port}
#    ?registry-type=${nacos.registry-type}
  protocol:
    name: tri
    serialization: protobuf
```

Pls. provide [GitHub address] to reproduce this issue.

### Expected Result

![image](https://user-images.githubusercontent.com/50915608/130789754-e2940dd9-1e08-43b6-b67e-aef4d3f77426.png)

### Actual Result

![image](https://user-images.githubusercontent.com/50915608/130886455-753a9d8f-fe18-48ac-8bd1-9da7376dcd41.png)

If there is an exception, please attach the exception trace:

java.lang.IllegalStateException: Failed to check the status of the service service.HelloService. No provider available for the service service.HelloService from the url dubbo://

**Comment by plusmancn** [comment]
I have reproduced this problem, and the problem can be more specific:  

The Triple protocol is not working on Spring integrated with Dubbo.

**Comment by plusmancn** [comment]
@feng996  I have found the cause of the problem which is not related to `dubbo-spring-boot-starter` as I first thought.

The source is in `org.apache.dubbo.config.metadata.ServiceInstanceHostPortCustomizer `,  let's have a look:
```java
@Override
public void customize(ServiceInstance serviceInstance) {
    String host = null;
    int port = -1;
    // ......
    Set<URL> urls = writableMetadataService.getExportedServiceURLs();
    if (CollectionUtils.isNotEmpty(urls)) {
        ApplicationModel applicationModel = serviceInstance.getApplicationModel();
        String preferredProtocol = applicationModel.getCurrentConfig().getProtocol();
        //  The default value of preferredProtocol is dubbo.
        if (preferredProtocol != null) {
            for (URL exportedURL : urls) {
                // The protocol of exportedURL is tri
                // because of tri != dubbo, the host and port will not be assigned values.
                if (preferredProtocol.equals(exportedURL.getProtocol())) {
                    host = exportedURL.getHost();
                    port = exportedURL.getPort();
                    break;
                }
            }
        } else {
            URL url = urls.iterator().next();
            host = url.getHost();
            port = url.getPort();
        }
        // If not the port of instace > 0, the application instance will not be registered to RegistryCenter(like Nacos, Zookeeper).
        // As a result, the consumer can't find the avaliabe providers when our settging is registry-mode=instance
        if (serviceInstance instanceof DefaultServiceInstance) {
            DefaultServiceInstance instance = (DefaultServiceInstance) serviceInstance;
            instance.setHost(host);
            instance.setPort(port);
        }
    }
}
```

For the moment, if you want both consumer and provider to force using `Application Discovery` in tri protocol, just change one line config of provider as follows:
```yaml
dubbo:
  application:
    metadata-type: remote
    register-mode: instance
    protocol: tri  <==== HERE, set preferredProtocol as tri
```

But, Dubbo official also needs to do two things for further promotion:
1. Complete the docs: [Triple协议迁移指南](https://dubbo.apache.org/zh/docs/migration/migration-triple/) as soon as possible
2. The logic of preferredProtocol was not user-friendly, we maybe should optimize it.
