### ISSUE TITLE
我又贡献bug来了！！！所有的check=true使用方式全部失效！

### ISSUE THREAD

**Issue by startjava** [apache/dubbo#8691]
```
spring:
  application:
    name: my-check1

# 配置dubbo
dubbo:
  registry:
    # 注册中心地址
    address: zookeeper://127.0.0.1
    port: 2181
  reference:
    com.ghy.www.api.IService1.check: true

server:
  port: 8085
```

```
@Configuration
public class JavaConfigDubbo {
    @DubboReference(check = true)
    private IService1 service1;
}
```

```
spring:
  application:
    name: my-check3

# 配置dubbo
dubbo:
  registry:
    # 注册中心地址
    address: zookeeper://127.0.0.1
    port: 2181
  consumer:
    check: true

server:
  port: 8085
```

```
spring:
  application:
    name: my-check4

# 配置dubbo
dubbo:
  registry:
    # 注册中心地址
    address: zookeeper://127.0.0.1
    port: 2181
    check: true

server:
  port: 8085
```

这四种使用方式，，在没有提供者时，，消费者能正常的启动，并且启动时控制台不出现异常，这是错误的，有bug的！
