### ISSUE TITLE
instance group in nacos registry always be DEFAULT_GROUP when dubbo.application.register-mode=instance or all

### ISSUE THREAD

**Issue by naah69** [apache/dubbo#8933]
### Environment

* Dubbo version: 3.0.2
* Operating System version: win10
* Java version: jdk11

### Steps to reproduce this issue

instance group in nacos registry always be DEFAULT_GROUP when `dubbo.application.register-mode=all or instance` and `dubbo.registry.group=dubbo`

```yaml
dubbo:
  protocol:
    charset: UTF-8
    server: netty4
    register: true
    name: tri
    serialization: protostuff
    port: -1
  provider:
    dynamic: true
    version: 1.0.0
    validation: true
  consumer:
    validation: true
    version: 1.0.0
  application:
    name: ${spring.application.name}
    compiler: javassist
    register-mode: all
    protocol: tri
  #    service-discovery:
  #      migration: FORCE_APPLICATION
  registry:
    use-as-metadata-center: false
    group: dubbo
    parameters:
      group: dubbo
      namespace: ${spring.profiles.active}
```

![image](https://user-images.githubusercontent.com/25682169/134857720-d93a7c2b-ba16-4d3f-816d-74e8564b34fd.png)

![image](https://user-images.githubusercontent.com/25682169/134857783-3925a695-63e9-459d-9ef4-4526bf000e07.png)

### Expected Result

instance group will be dubbo
