### ISSUE TITLE
在 spring boot  中使用 dubbo, 对注解 @DubboReference 依赖， 希望可以提供 @MockBean 的功能

### ISSUE THREAD

**Issue by ooooo-youwillsee** [apache/dubbo#9116]

**Comment by ooooo-youwillsee** [comment]
The following is my code

```
@Slf4j
@SpringBootApplication
public class DubboConsumerApplication {

	@DubboReference
	private UserService userService;

	public static void main(String[] args) {
		SpringApplication.run(DubboConsumerApplication.class, args);
	}

	@Bean
	public ApplicationRunner testApplicationRunner() {
		return __ -> {
			String username = userService.getUsernameById(1L);
			log.info("username: {}", username);
		};
	}
}
``` 

```
@SpringBootTest
class DubboConsumerApplicationTest {

	@MockBean
	private UserService userService;

	@Test
	public void testDubboReferenceMockBean() {
		when(userService.getUsernameById(any())).thenReturn("mock username");

		String username1 = userService.getUsernameById(1L);
		assertEquals("mock username", username1);

		String username2 = userService.getUsernameById(1L);
		assertEquals("mock username", username2);
	}
}
```

bootstrap.yml

```
spring:
  application:
    name: demo-spring-cloud-dubbo-consumer
dubbo:
  protocols:
    dubbo:
      name: dubbo
      port: -1
  registry:
    address: N/A
#    address: 224.5.6.7:2222  # No matter what is configured, the error is reported
  scan:
    base-packages: com.ooooo
  consumer:
    check: false
```

dependencies

```
mavenBom "com.alibaba.cloud:spring-cloud-alibaba-dependencies:2.2.6.RELEASE"
mavenBom "org.springframework.cloud:spring-cloud-dependencies:Hoxton.SR10"
//=========
    api('org.springframework.boot:spring-boot-starter-web')
    api('com.alibaba.cloud:spring-cloud-starter-dubbo')
    api('com.alibaba.cloud:spring-cloud-starter-alibaba-nacos-discovery')
```


You can find the code [here](https://github.com/ooooo-youwillsee/java-framework-guide/tree/main/spring-cloud-examples/spring-cloud-dubbo/spring-cloud-dubbo-consumer)
