### ISSUE TITLE
基于3.0.0使用triple协议实现“应用级发现”失败，WARN日志“instance hasn't been registered yet”

### ISSUE THREAD

**Issue by YuWan1117** [apache/dubbo#9295]
- [ ] I have searched the [issues](https://github.com/apache/dubbo/issues) of this repository and believe that this is not a duplicate.

## Ask your question here
基于3.0.0版本使用triple协议、zookeeper注册中心，配置provider仅通过应用级发现`dubbo.application.register-mode=instance`，启动服务后观察ZK的services/路径下对应服务并没有注册成功。
- 配置信息如下
```
dubbo:
  application:
    name: hello-service # 应用名
    qos-enable: false
    logger: slf4j
    register-mode: instance
  protocols:
    tri:
      name: tri
      port: 20880
      threads: 500
#    dubbo:
#      name: dubbo
#      port: 20415
#      threads: 500
  registry:
    address: ${zookeeper_host}
    protocol: zookeeper
    parameters:
      register-type: service
```
- 报错信息如下
```
[WARN ] [2021-11-18 16:29:17.156] [Dubbo-framework-scheduler-thread-1] [] [] [ServiceInstanceMetadataUtils.lambda$refreshMetadataAndInstance$1:267] [ [DUBBO] Refreshing of service instance started, but instance hasn't been registered yet., dubbo version: 3.0.0, current host: 172.X.X.X]
```
#### 3.0.0版本
- 使用3.0.0版本，provider端基于双注册协议（dubbo+triple）启动后ZK上成功显示对应的注册信息（consumer可以通过实例正常访问）
- 使用3.0.0版本，provider端基于dubbo协议启动后ZK成功显示对应的注册信息（consumer可以通过实例正常访问）
#### 3.0.4版本
- 使用3.0.4版本，provider端基于triple协议启动后ZK成功显示对应的注册信息（consumer可以通过实例正常访问）
**NOTE**：
> 在3.0.4版本基于triple协议的测试中，除了dubbo版本不一样外，其他配置、代码均一致。因此想确认下3.0.0版本是不是本就存在问题（对应报错信息见上面的内容），具体问题是什么？如何fix，对应的commit信息是哪里？
- 3.0.4版本基于应用级注册成功后的ZK信息如下
```
{
    "name":"hello-service",
    "id":"172.16.128.132:20880",
    "address":"172.16.128.132",
    "port":20880,
    "sslPort":null,
    "payload":{
        "@class":"org.apache.dubbo.registry.zookeeper.ZookeeperInstance",
        "id":null,
        "name":"hello-service",
        "metadata":{
            "dubbo.endpoints":"[{\"port\":20880,\"protocol\":\"tri\"}]",
            "dubbo.metadata-service.url-params":"{\"version\":\"1.0.0\",\"dubbo\":\"2.0.2\",\"release\":\"3.0.4\",\"port\":\"20881\",\"protocol\":\"dubbo\"}",
            "dubbo.metadata.revision":"29c5c4f1c855128336eb2ff7c8a71d47",
            "dubbo.metadata.storage-type":"local"
        }
    },
    "registrationTimeUTC":1637223402423,
    "serviceType":"DYNAMIC",
    "uriSpec":null
}
```

##### 期待大家针对3.0.0版本triple协议的应用级发现的相关讨论以及大佬们的指点！ 感谢！
