### ISSUE TITLE
dubbo使用nacos的配置中心之后会疯狂往配置中心写入配置, 这个正常吗?

### ISSUE THREAD

**Issue by HaoLi-Rainbow** [apache/dubbo#9306]
问题:

dubbo使用nacos的配置中心之后会疯狂往配置中心写入配置, 我们一共就8个项目, dubbo写入的配置文件就写了50个, 这个正常吗?

使用版本

```xml
        <dependency>
            <groupId>com.alibaba.cloud</groupId>
            <artifactId>spring-cloud-starter-alibaba-nacos-config</artifactId>
            <version>2.2.2.RELEASE</version>
        </dependency>
        <dependency>
            <groupId>com.alibaba.cloud</groupId>
            <artifactId>spring-cloud-starter-alibaba-nacos-discovery</artifactId>
            <version>2.2.2.RELEASE</version>
        </dependency>
        <dependency>
            <groupId>org.apache.dubbo</groupId>
            <artifactId>dubbo-spring-boot-starter</artifactId>
            <version>2.7.8</version>
        </dependency>
        <dependency>
            <groupId>org.apache.dubbo</groupId>
            <artifactId>dubbo-registry-nacos</artifactId>
            <version>2.7.8</version>
        </dependency>
```

配置文件

```yaml
dubbo:
  registry:
    address: nacos://${spring.cloud.nacos.discovery.server-addr}
    parameters[namespace]: ${spring.cloud.nacos.discovery.namespace}
  consumer:
    # 关闭所有服务的启动时检查 (没有提供者时报错)
    check: false
  protocol:
    name: dubbo
    port: -1
```

结果(每页10个, 已经有50个了)

![image-20211123105735738](https://user-images.githubusercontent.com/49888630/142965157-b8533cbf-0726-405f-8c4d-a15c25d07adc.png)

**Comment by leyou240** [comment]
这个是元数据信息

**Comment by HaoLi-Rainbow** [comment]
> 这个是元数据信息

要保留吗, 我看nacos每个命名空间有200个配置文件的限制, 现在dubbo都用了50个, 后面可能会更多

**Comment by zuonidelaowang** [comment]
> 
你看看我这个设置后，能不能调用
https://github.com/apache/dubbo/issues/9293

太多元数据写入nacos, 影响nacos性能

**Comment by zuonidelaowang** [comment]
> 这个是元数据信息

禁用元数据写入nacos，comsumer 启动就报错，这个怎么解决？知道不？
https://github.com/apache/dubbo/issues/9293

**Comment by leyou240** [comment]
> > 这个是元数据信息
> 
> 要保留吗, 我看nacos每个命名空间有200个配置文件的限制, 现在dubbo都用了50个, 后面可能会更多
我按这个方式使用，没有发现有问题。使用的是dubbo3.0.4版本
```
dubbo:
  registry:
    address: nacos://xxx:8848
    username: 
    password: 
    use-as-metadata-center: false
```

**Comment by zuonidelaowang** [comment]
> > > 这个是元数据信息
> > 
> > 
> > 要保留吗, 我看nacos每个命名空间有200个配置文件的限制, 现在dubbo都用了50个, 后面可能会更多
> 
> 我按这个方式使用，没有发现有问题。使用的是dubbo3.0.4版本
> 
> ```
> dubbo:
>   registry:
>     address: nacos://xxx:8848
>     username: 
>     password: 
>     use-as-metadata-center: false
> ```

那你这个还是基于接口级别的注册，你试试加入这个配置，consumer 还能不能正常启动
```
dubbo:
  registry:
    address: nacos://${nacos.server}?registry-type=service

**Comment by HaoLi-Rainbow** [comment]
> ```
>     use-as-metadata-center: false
> ```

不行我会报错
`No provider available from registry 10.xx.xx.123:8848 for service com.xxx.comn.service.rate.IBasisCurrencyRateSV on consumer 10.xx.xx.122 use dubbo version 2.7.8, please check status of providers(disabled, not registered or in blacklist).`

**Comment by HaoLi-Rainbow** [comment]
> > > > 这个是元数据信息
> > > 
> > > 
> > > 要保留吗, 我看nacos每个命名空间有200个配置文件的限制, 现在dubbo都用了50个, 后面可能会更多
> > 
> > 
> > 我按这个方式使用，没有发现有问题。使用的是dubbo3.0.4版本
> > ```
> > dubbo:
> >   registry:
> >     address: nacos://xxx:8848
> >     username: 
> >     password: 
> >     use-as-metadata-center: false
> > ```
> 
> 那你这个还是基于接口级别的注册，你试试加入这个配置，consumer 还能不能正常启动
> 
> ```
> dubbo:
>   registry:
>     address: nacos://${nacos.server}?registry-type=service
> ```

不行我会报错
No provider available from registry 10.xx.xx.123:8848 for service com.xxx.comn.service.rate.IBasisCurrencyRateSV on consumer 10.xx.xx.122 use dubbo version 2.7.8, please check status of providers(disabled, not registered or in blacklist).

**Comment by zuonidelaowang** [comment]
> providers

找不到provider ，我也是，但是我看他们说最新版已经不会写入配置文件到 配置中心了，不知道怎么配置。自动生成一大堆配置文件到nacos, 直接超过nacos上限了，蛋疼。

**Comment by zuonidelaowang** [comment]
> > > > > 这个是元数据信息
> > > > 
> > > > 
> > > > 要保留吗, 我看nacos每个命名空间有200个配置文件的限制, 现在dubbo都用了50个, 后面可能会更多
> > > 
> > > 
> > > 我按这个方式使用，没有发现有问题。使用的是dubbo3.0.4版本
> > > ```
> > > dubbo:
> > >   registry:
> > >     address: nacos://xxx:8848
> > >     username: 
> > >     password: 
> > >     use-as-metadata-center: false
> > > ```
> > 
> > 
> > 那你这个还是基于接口级别的注册，你试试加入这个配置，consumer 还能不能正常启动
> > ```
> > dubbo:
> >   registry:
> >     address: nacos://${nacos.server}?registry-type=service
> > ```
> 
> 不行我会报错 No provider available from registry 10.xx.xx.123:8848 for service com.xxx.comn.service.rate.IBasisCurrencyRateSV on consumer 10.xx.xx.122 use dubbo version 2.7.8, please check status of providers(disabled, not registered or in blacklist).

找不到provider ，我也是，但是我看他们说最新版已经不会写入配置文件到 配置中心了，不知道怎么配置。自动生成一大堆配置文件到nacos, 直接超过nacos上限了。

**Comment by HaoLi-Rainbow** [comment]
> > > > > > 这个是元数据信息
> > > > > 
> > > > > 
> > > > > 要保留吗, 我看nacos每个命名空间有200个配置文件的限制, 现在dubbo都用了50个, 后面可能会更多
> > > > 
> > > > 
> > > > 我按这个方式使用，没有发现有问题。使用的是dubbo3.0.4版本
> > > > ```
> > > > dubbo:
> > > >   registry:
> > > >     address: nacos://xxx:8848
> > > >     username: 
> > > >     password: 
> > > >     use-as-metadata-center: false
> > > > ```
> > > 
> > > 
> > > 那你这个还是基于接口级别的注册，你试试加入这个配置，consumer 还能不能正常启动
> > > ```
> > > dubbo:
> > >   registry:
> > >     address: nacos://${nacos.server}?registry-type=service
> > > ```
> > 
> > 
> > 不行我会报错 No provider available from registry 10.xx.xx.123:8848 for service com.xxx.comn.service.rate.IBasisCurrencyRateSV on consumer 10.xx.xx.122 use dubbo version 2.7.8, please check status of providers(disabled, not registered or in blacklist).
> 
> 找不到provider ，我也是，但是我看他们说最新版已经不会写入配置文件到 配置中心了，不知道怎么配置。自动生成一大堆配置文件到nacos, 直接超过nacos上限了。



这样注册dubbo就不会往config里面写入了

```yaml
dubbo:
  application:
    name: ${spring.application.name}
  registry:
    address: nacos://${spring.cloud.nacos.discovery.server-addr}
    parameters[namespace]: ${spring.cloud.nacos.discovery.namespace}
    use-as-metadata-center: false
    use-as-config-center: false
  consumer:
    # 关闭所有服务的启动时检查 (没有提供者时报错)
    check: false
  protocol:
    name: dubbo
    port: -1

```
