### ISSUE TITLE
重启服务消费者，会无法找到服务提供者，需要再次重启服务提供者

### ISSUE THREAD

**Issue by wenlincheng** [apache/dubbo#9661]
dubbo-spring-boot-starter 2.7.15
springboot 2.3.2.RELEASE
使用nacos 2.0.3 / 1.4.1 作为注册中心

依次启动服务提供者和消费者，能正常调用，当重启服务消费者，调用会报无法找到服务提供者 org.apache.dubbo.rpc.RpcException: No provider available from registry xxxxx:80 for service ....... 再重启服务提供者，则恢复正常

配置
```
# Dubbo
dubbo:
  scan:
    # dubbo 服务扫描基准包
    base-packages: com.xxxx.xxxx.item.service
  # 协议
  protocols:
    # dubbo 协议
    dubbo:
      name: dubbo
      port: -1
  registry:
    address: nacos://xxxxx:80/?username=nacos&password=nacos&namespace=${spring.profiles.active}&group=ARK_SAILOR
  application:
    qos-enable: false
    logger: slf4j
  consumer:
    check: false
```
