### ISSUE TITLE
使用dubbo连接zookeeper集群时，消费者启动时出现节点已存在的异常。

### ISSUE THREAD

**Issue by startjava** [apache/dubbo#9729]
提供者配置：
```
# 应用名称
spring:
  application:
    name: my-multi-registrycenter-provider

# 配置dubbo
dubbo:
  registries:
    provider1:
      address: zookeeper://192.168.0.103
      port: 2181
      provider2:
        address: zookeeper://192.168.0.140
        port: 2181
      provider3:
        address: zookeeper://192.168.0.62
        port: 2181
  scan:
    base-packages: com.ghy.www.my.multi.registrycenter.provider.service # 扫包
  application:
    logger: slf4j
```

消费者配置：
```
# 应用名称
spring:
  application:
    name: my-multi-registrycenter-consumer

server:
  port: 8085

# 配置dubbo
dubbo:
  registries:
    provider1:
      address: zookeeper://192.168.0.103
      port: 2181
    provider2:
      address: zookeeper://192.168.0.140
      port: 2181
    provider3:
      address: zookeeper://192.168.0.62
      port: 2181
  application:
    logger: slf4j
```

服务提供者启动没有出现异常，而服务消费者启动出现异常。

3台zookeeper服务器集群状态正常。

[zk集群消费者启动报错.txt](https://github.com/apache/dubbo/files/8159413/zk.txt)
