### ISSUE TITLE
triple协议使用跑不起，帮忙看一下问题出在那，网上使用triple协议demo好像都不太完善。

### ISSUE THREAD

**Issue by gang0713** [apache/dubbo#9733]
demo地址：https://wwe.lanzouf.com/i1agk00x9bla

报错如下：

2022-03-03 11:15:38  INFO cn.raysonblog.shopserviceconsumer.ShopServiceConsumerApplication:61 - Started ShopServiceConsumerApplication in 9.072 seconds (JVM running for 10.303)
2022-03-03 11:16:00 ERROR org.springframework.scheduling.support.TaskUtils$LoggingErrorHandler:95 - Unexpected error occurred in scheduled task
org.apache.dubbo.rpc.RpcException: Failed to invoke the method sayHello in the service cn.raysonblog.shopservice.api.service.RpcShopService. No provider available for the service dev/cn.raysonblog.shopservice.api.service.RpcShopService:1.0.0 from registry 127.0.0.1:8848 on the consumer 192.168.0.112 using the dubbo version 3.0.5. Please check if the providers have been started and registered.
	at org.apache.dubbo.rpc.cluster.support.AbstractClusterInvoker.checkInvokers(AbstractClusterInvoker.java:355) ~[dubbo-3.0.5.jar:3.0.5]

**Comment by rainwolf01** [comment]
```
  registry:
    address: nacos://${nacosserver.server-addr}?registry-type=service&username=${nacosserver.username}&password=${nacosserver.password}
    parameters:
      namespace: ${nacosserver.namespace}
```
如果是`应用级`要指定这个参数`registry-type=service`，provider起来后看看nacos的服务列表里有没有provider服务
