### ISSUE TITLE
dubbo 3.0.6 Failed register interface application mapping for service

### ISSUE THREAD

**Issue by xtuul** [apache/dubbo#9742]
nacos 2.0.4
dubbo 3.0.6

配置：
-Ddubbo.application.register-mode=all

启动发生异常，接口级地址和应用级地址不能同时在nacos上注册，异常信息如下：
`2022-03-07 14:47:05.169 ERROR 18988 --- [           main] org.apache.dubbo.config.ServiceConfig    :  [DUBBO] Failed register interface application mapping for service dubbo-provider/org.apache.dubbo.metadata.MetadataService:1.0.0, dubbo version: 3.0.6, current host: 192.168.137.1`

使用dubbo 3.0.5 是OK的

**Comment by xtuul** [comment]
接口级地址和应用级地址不能同时注册

**Comment by rainwolf01** [comment]
我用`3.0.5`没这个错，发现`3.0.6`增加的这段错误信息，输出了同样的Error信息。我的配置是:
```
dubbo:
  application:
    metadata-type: local
    register-mode: instance
```
@chickenlj
