### ISSUE TITLE
dubbo 3.0.7: serviceNameMapping not found serviceName if provider metacenter disabled 

### ISSUE THREAD

**Issue by rainwolf01** [apache/dubbo#9992]
- [ x ] I have searched the [issues](https://github.com/apache/dubbo/issues) of this repository and believe that this is not a duplicate.

dubbo 3.0.5 ok, but failed 3.0.7. We use `registry-type=service`,  `metadata-center` is disabled.

### Environment

* Dubbo version: 3.0.7
* Operating System version: Spring Boot 2.5.12
* Java version: jdk 11

### Steps to reproduce this issue

1. properties config(via yaml)
```
dubbo:
  registry:
    address: nacos://127.0.0.1:8848?registry-type=service&username=nacos&password=nacos
    use-as-config-center: false
    use-as-metadata-center: false
```

Pls. provide [GitHub address] to reproduce this issue.

### Actual Behavior

If there is an exception, please attach the exception trace:

```
Just put your stack trace here!
```
